#' @include agent-definition.R delegation-manifest.R delegation-binding.R delegation-inspection.R delegation-observation.R
NULL

# Multi-agent orchestration for deputy

deputy_lead_routing_start_marker <-
  "<!-- deputy-lead-routing:v1:start -->"
deputy_lead_routing_end_marker <-
  "<!-- deputy-lead-routing:v1:end -->"

#' Agent that delegates to subagents
#'
#' @description
#' An [Agent] that can hand tasks to subagents. Its model gets a
#' `delegate_to_agent` tool for picking a registered [agent_definition()];
#' each delegation runs a new subagent in its own conversation and returns
#' its answer. See `vignette("multi-agent")`.
#'
#' @export
LeadAgent <- R6::R6Class(
  "LeadAgent",
  inherit = Agent,

  public = list(
    #' @description
    #' Create a new LeadAgent.
    #'
    #' @param chat An ellmer `Chat` for the lead.
    #' @param sub_agents A list of [agent_definition()] objects.
    #' @param tools Tools for the lead, in addition to `delegate_to_agent`.
    #' @param system_prompt System prompt for the lead; a list of the
    #'   subagents is appended.
    #' @param permissions [Permissions] for the lead and, by default, its
    #'   subagents. A definition can only narrow them.
    #' @param usage_limits [UsageLimits] for each lead run, shared with the
    #'   subagents it starts.
    #' @param context_policy A [ContextPolicy] for compaction and large tool
    #'   results, used by the lead and its subagents.
    #' @param enable_file_checkpointing Whether to checkpoint files before
    #'   Deputy's file tools change them, so changes can be rewound. The lead
    #'   and its subagents share the checkpoints.
    #' @param file_checkpoint_max_file_bytes Maximum size, in bytes, of one file
    #'   saved in a checkpoint. Defaults to 50 MiB.
    #' @param file_checkpoint_max_journal_bytes Maximum total size, in bytes, of
    #'   all checkpoint data. Defaults to 250 MiB.
    #' @param working_dir Working directory, shared with subagents.
    #' @param session_id Optional session ID, generated by default.
    #' @param run_context Named list of JSON-compatible values, such as a user
    #'   ID, attached to every run of the lead and its subagents.
    #' @param agent_id Optional ID for the lead, generated by default.
    #' @param agent_name Optional display name for the lead.
    #' @param fallback_chats Chats to switch to, in order, if the lead's
    #'   provider fails; see [Agent]. Subagents have no fallbacks; those that
    #'   inherit the lead's model use its current chat.
    #' @param delegation_sources Text sources that tasks can cite as evidence
    #'   (see [DelegationInput]): an unnamed list of up to 128 records, 16 MiB in
    #'   total, each with `source_id`, `revision`, `owner_id`, `conversation_id`
    #'   and `text`, and optionally `allowed_agents`, the definitions that may
    #'   receive it (`NULL` for all). Each `source_id` may have one revision per
    #'   owner and conversation. Deputy checks the scope and revision, not
    #'   whether the user may see a source, so include only sources they may see.
    #' @param delegation_scope A list with `owner_id` and `conversation_id`,
    #'   required with `delegation_sources`. Only sources with the same owner and
    #'   conversation can be used, and the model can't change it. It is also
    #'   passed to the [DelegationDisclosure] `authorize` function.
    #' @param delegation_policy A [DelegationPolicy] for subagent tools, hooks
    #'   and user questions.
    #' @param delegation_disclosure A [DelegationDisclosure] that decides who may
    #'   inspect subagents and their history. The default denies everyone.
    #' @param delegation_observation A [DelegationObservation] setting the size
    #'   of the event buffer read by `$observe_subagents()`.
    #' @param approval_dir Optional directory for durable tool approvals; see
    #'   [Agent]. A lead with `approval_dir` set can't delegate.
    #' @param trusted_results Optional [TrustedResults] policy that also covers
    #'   every subagent and its tools. A designated tool may belong to the lead
    #'   or a subagent, but must be the same tool everywhere. Subagents' trusted
    #'   results are recorded in the lead's run and passed to its `on_result`.
    #' @param delegation_max_bytes Size limit, in bytes, checked separately for
    #'   a delegation's task, evidence, starting prompt and message, and
    #'   [DelegationManifest]. Defaults to 64 KiB. A delegation over this limit,
    #'   or whose estimated tokens exceed the [ContextPolicy] `max_tokens`,
    #'   fails before any model request.
    #' @return A new `LeadAgent` object
    initialize = function(
      chat,
      sub_agents = list(),
      tools = list(),
      system_prompt = NULL,
      permissions = NULL,
      usage_limits = NULL,
      context_policy = ContextPolicy(),
      enable_file_checkpointing = FALSE,
      file_checkpoint_max_file_bytes = 50 * 1024^2,
      file_checkpoint_max_journal_bytes = 250 * 1024^2,
      working_dir = getwd(),
      session_id = NULL,
      run_context = list(),
      agent_id = NULL,
      agent_name = NULL,
      fallback_chats = list(),
      delegation_sources = list(),
      delegation_scope = list(),
      delegation_max_bytes = 65536L,
      delegation_policy = DelegationPolicy(),
      delegation_disclosure = DelegationDisclosure(),
      delegation_observation = DelegationObservation(),
      approval_dir = NULL,
      trusted_results = NULL
    ) {
      if (!is.null(private$.chat)) {
        check_conversation_initialization(self)
      }
      check_incoming_conversation(chat)
      if (!S7::S7_inherits(delegation_policy, DelegationPolicy)) {
        delegation_binding_abort(
          "delegation_policy must be a DelegationPolicy."
        )
      }
      if (!S7::S7_inherits(delegation_disclosure, DelegationDisclosure)) {
        cli::cli_abort("delegation_disclosure must be a DelegationDisclosure.")
      }
      if (!S7::S7_inherits(delegation_observation, DelegationObservation)) {
        cli::cli_abort(
          "delegation_observation must be a DelegationObservation."
        )
      }
      private$.delegation_buffer <- new_delegation_buffer(
        delegation_observation
      )
      private$.delegation_disclosure <- delegation_disclosure
      private$.delegation_policy <- delegation_policy
      sources <- normalize_delegation_sources(
        delegation_sources,
        delegation_scope
      )
      private$delegation_sources <- sources$sources
      private$delegation_scope <- sources$scope
      private$delegation_max_bytes <- context_policy_whole_number(
        delegation_max_bytes,
        "delegation_max_bytes"
      )
      if (is.null(private$delegation_max_bytes)) {
        delegation_input_abort(
          "invalid",
          "delegation_max_bytes must be finite."
        )
      }
      private$.sub_agent_defs <- normalize_agent_definitions(sub_agents)

      # Build enhanced system prompt
      enhanced_prompt <- private$build_lead_prompt(
        system_prompt,
        private$.sub_agent_defs
      )

      # Create the delegate tool
      delegate_tool <- private$create_delegate_tool()

      # Combine tools
      all_tools <- c(list(delegate_tool), tools)

      # Call parent constructor
      super$initialize(
        delegation_scope = sources$scope,
        delegation_disclosure = delegation_disclosure,
        delegation_observation = delegation_observation,
        chat = chat,
        tools = all_tools,
        system_prompt = enhanced_prompt,
        permissions = permissions,
        usage_limits = usage_limits,
        context_policy = context_policy,
        enable_file_checkpointing = enable_file_checkpointing,
        file_checkpoint_max_file_bytes = file_checkpoint_max_file_bytes,
        file_checkpoint_max_journal_bytes = file_checkpoint_max_journal_bytes,
        working_dir = working_dir,
        session_id = session_id,
        run_context = run_context,
        agent_id = agent_id,
        agent_name = agent_name,
        fallback_chats = fallback_chats,
        approval_dir = approval_dir,
        trusted_results = trusted_results
      )
    },

    #' @description
    #' Add a subagent definition. Errors if its name is already registered.
    #'
    #' @param definition An [agent_definition()] object
    #' @return The lead, invisibly.
    register_sub_agent = function(definition) {
      check_conversation_lease(self, NULL)
      if (!S7::S7_inherits(definition, AgentDefinition)) {
        cli_abort("{.arg definition} must be an AgentDefinition object")
      }

      definition <- copy_agent_definition(definition)
      if (definition$name %in% names(private$.sub_agent_defs)) {
        cli_abort(
          "AgentDefinition {.val {definition$name}} is already registered"
        )
      }
      private$.sub_agent_defs[[definition$name]] <- definition
      tryCatch(
        private$check_trusted_tools(private$.chat$get_tools()),
        error = function(error) {
          private$.sub_agent_defs[[definition$name]] <- NULL
          rlang::cnd_signal(error)
        }
      )

      # Replace only the generated routing section so compaction summaries,
      # skills, and hook-provided context remain intact.
      current_prompt <- private$.chat$get_system_prompt()
      new_prompt <- private$replace_lead_prompt(
        current_prompt,
        private$.sub_agent_defs
      )
      private$.chat$set_system_prompt(new_prompt)

      cli_alert_info("Registered sub-agent: {.val {definition$name}}")
      invisible(self)
    },

    #' @description
    #' List the names of the registered subagent definitions.
    #'
    #' @return A character vector.
    available_sub_agents = function() {
      unname(vapply(
        private$.sub_agent_defs,
        function(definition) definition$name,
        character(1)
      ))
    },

    #' @description
    #' Ask several subagents for one reply each, in parallel.
    #'
    #' Each named definition gets a fresh conversation, no tools and at most
    #' one model request, so definitions with tools, skills or `mcp_servers`
    #' are rejected. The lead's conversation is not changed.
    #' @param tasks A named character vector, or a named list of strings and
    #'   [DelegationInput] objects. Each name selects a different registered
    #'   definition.
    #' @param max_active Maximum number of subagents running at once.
    #' @param mode Only `"stateless"` is supported.
    #' @param usage_limits Optional [UsageLimits] for the whole batch; unset
    #'   fields use the lead's. Token and cost limits are split between the
    #'   subagents running at once and checked after each reply, so the batch
    #'   can overshoot by one reply per running subagent.
    #' @param run_context Named list added to the lead's `run_context` for this
    #'   batch.
    #' @return A list with `mode`, `results` ([AgentResult] objects, `NULL`
    #'   where none was returned), `outcomes` ([DelegationOutcome] objects),
    #'   `errors`, `status`, and `run`, an [AgentResult] for the whole batch
    #'   that `$last_run()` also returns. Entries follow the order of `tasks`,
    #'   including failed and unstarted ones; a failure doesn't discard the
    #'   other results.
    parallel_delegate = function(
      tasks,
      max_active = 2L,
      mode = "stateless",
      usage_limits = NULL,
      run_context = list()
    ) {
      promise <- self$parallel_delegate_async(
        tasks,
        max_active,
        mode,
        usage_limits,
        run_context
      )
      tryCatch(
        private$resolve_promise(promise),
        interrupt = function(condition) {
          self$interrupt()
          try(private$resolve_promise(promise), silent = TRUE)
          stop(condition)
        }
      )
    },

    #' @description
    #' Version of `$parallel_delegate()` that doesn't block R.
    #' @param tasks,max_active,mode,usage_limits,run_context See
    #'   `$parallel_delegate()`.
    #' @return A promise that resolves to the same list as
    #'   `$parallel_delegate()`. Calling `$interrupt()` cancels tasks that
    #'   haven't started and asks running subagents to stop.
    parallel_delegate_async = function(
      tasks,
      max_active = 2L,
      mode = "stateless",
      usage_limits = NULL,
      run_context = list()
    ) {
      lead_parallel_delegate(
        self,
        tasks,
        max_active,
        mode,
        usage_limits,
        run_context
      )
    },

    #' @description
    #' Ask the lead and its running subagents to stop.
    #' @param reason Reason recorded on the stopped runs.
    #' @return Invisibly, whether the lead or a subagent was running.
    interrupt = function(reason = "interrupted") {
      super$interrupt(reason)
    },

    #' @description
    #' Print the lead and the names of its subagent definitions.
    print = function() {
      super$print()
      cli::cat_line(cli::cli_format_method({
        cli::cli_div(theme = list(div = list("margin-left" = 2)))
        cli::cli_text("sub_agents: {length(private$.sub_agent_defs)}")
        if (length(private$.sub_agent_defs) > 0) {
          names <- self$available_sub_agents()
          cli::cli_text("{paste(names, collapse = \", \")}")
        }
      }))
      invisible(self)
    }
  ),

  active = list(
    #' @field sub_agent_defs A copy of the registered definitions. Use
    #'   `$register_sub_agent()` to add one.
    sub_agent_defs = function(value) {
      if (!missing(value)) {
        cli_abort("{.field sub_agent_defs} is read-only")
      }
      unname(lapply(private$.sub_agent_defs, copy_agent_definition))
    }
  ),

  private = list(
    # Build the lead agent's system prompt
    build_lead_prompt = function(base_prompt, sub_agents) {
      lines <- character()

      if (!is.null(base_prompt)) {
        lines <- c(lines, base_prompt, "")
      }

      if (length(sub_agents) > 0) {
        lines <- c(
          lines,
          deputy_lead_routing_start_marker,
          "# Available Sub-Agents",
          "",
          "You can delegate specialized tasks to these sub-agents using the",
          "`delegate_to_agent` tool:",
          ""
        )

        for (def in sub_agents) {
          lines <- c(lines, paste0("## ", def$name), def$description, "")
        }

        lines <- c(
          lines,
          "When delegating, provide a clear task description. The sub-agent",
          "will complete the task and return results to you.",
          "",
          "# End Available Sub-Agents",
          deputy_lead_routing_end_marker,
          ""
        )
      }

      paste(lines, collapse = "\n")
    },

    replace_lead_prompt = function(full_prompt, sub_agents) {
      section <- private$build_lead_prompt(NULL, sub_agents)
      if (!is_nonempty_string(full_prompt)) {
        return(section)
      }

      start_marker <- deputy_lead_routing_start_marker
      end_marker <- deputy_lead_routing_end_marker
      start <- regexpr(start_marker, full_prompt, fixed = TRUE)
      if (start[[1L]] < 0L) {
        return(private$build_lead_prompt(full_prompt, sub_agents))
      }
      remainder <- substr(full_prompt, start[[1L]], nchar(full_prompt))
      end <- regexpr(end_marker, remainder, fixed = TRUE)
      if (end[[1L]] < 0L) {
        return(private$build_lead_prompt(full_prompt, sub_agents))
      }

      before <- substr(full_prompt, 1L, start[[1L]] - 1L)
      after_start <- start[[1L]] + end[[1L]] - 1L + attr(end, "match.length")
      after <- if (after_start > nchar(full_prompt)) {
        ""
      } else {
        substr(full_prompt, after_start, nchar(full_prompt))
      }
      paste0(before, section, after)
    },

    # Create the delegate_to_agent tool
    create_delegate_tool = function() {
      # Capture self for the closure
      lead_agent <- self

      tool <- ellmer::tool(
        fun = function(
          agent_name,
          task,
          constraints = character(),
          evidence = list(),
          deliverable = NULL,
          stop_conditions = character()
        ) {
          correlation <- private$claim_delegation(
            tool_name = "delegate_to_agent"
          )

          route_key <- if (is_nonempty_string(agent_name)) {
            tolower(trimws(agent_name))
          } else {
            ""
          }
          def <- private$.sub_agent_defs[[route_key]]

          if (is.null(def)) {
            available <- lead_agent$available_sub_agents()
            ellmer::tool_reject(paste0(
              "Unknown agent: ",
              agent_name,
              ". ",
              "Available agents: ",
              paste(available, collapse = ", ")
            ))
          }

          id <- lead_admit_delegation(lead_agent, def, task, correlation)
          child <- tryCatch(
            {
              input <- if (S7::S7_inherits(task, DelegationInput)) {
                if (
                  length(constraints) ||
                    length(evidence) ||
                    !is.null(deliverable) ||
                    length(stop_conditions)
                ) {
                  delegation_input_abort(
                    "invalid",
                    "Structured task cannot be combined with separate brief fields."
                  )
                }
                normalize_delegation_input(task)
              } else {
                DelegationInput(
                  task,
                  constraints,
                  delegation_tool_references(evidence),
                  deliverable,
                  stop_conditions
                )
              }
              prepared <- resolve_delegation_input(lead_agent, def, input)
              limits <- private$derive_subagent_usage_limits(def)
              child <- private$create_sub_agent(def, correlation, limits)
              manifest <- prepare_delegation_manifest(
                lead_agent,
                def,
                prepared,
                child
              )
              lead_bind_delegation(lead_agent, id, child, manifest)
              child
            },
            error = function(condition) {
              lead_settle_delegation(
                lead_agent,
                id,
                error = condition,
                stop_reason = "setup_error"
              )
              release_delegation_binding(lead_agent, id)
              stop(condition)
            }
          )
          # Reserve before returning the promise, so concurrent calls cannot
          # each receive the same remaining budget.
          private$reserve_delegation_usage(id, limits)
          cli::cli_alert_info("Delegating to {.val {def$name}}: {input$task}")
          lead_run_delegation(lead_agent, id, child, def, manifest$message) |>
            promises::then(function(outcome) {
              if (!is.null(private$current_usage_limits)) {
                limit <- usage_limit_status(
                  private$current_run_usage(),
                  private$current_usage_limits,
                  require_followup = TRUE
                )
                if (!is.null(limit)) private$mark_usage_limit(limit)
              }
              payload <- delegation_json(S7::props(delegation_outcome(
                private$subagent_runs[[id]],
                compact = TRUE
              )))
              if (!is.null(outcome$error)) {
                # Preserve the diagnostic label without repeating an unbounded
                # provider error; the bounded payload contains that message.
                ellmer::tool_reject(paste0(
                  "Subagent '",
                  inspection_text(def$name, 512L),
                  "' failed.\n",
                  payload
                ))
              }
              payload
            })
        },
        name = "delegate_to_agent",
        description = "Delegate a task to a specialized sub-agent. The sub-agent will complete the task and return results.",
        arguments = list(
          agent_name = ellmer::type_string(
            "Name of the sub-agent to delegate to"
          ),
          task = ellmer::type_string("The task to delegate to the Subagent"),
          constraints = ellmer::type_array(
            ellmer::type_string(),
            required = FALSE
          ),
          evidence = ellmer::type_array(
            ellmer::type_object(
              source_id = ellmer::type_string(),
              revision = ellmer::type_string()
            ),
            required = FALSE
          ),
          deliverable = ellmer::type_string(required = FALSE),
          stop_conditions = ellmer::type_array(
            ellmer::type_string(),
            required = FALSE
          )
        ),
        annotations = ellmer::tool_annotations(
          read_only_hint = FALSE,
          destructive_hint = FALSE,
          open_world_hint = FALSE,
          idempotent_hint = FALSE
        )
      )
      attr(tool, "deputy_delegation_tool") <- TRUE
      tool
    },

    # Create a sub-agent from a definition
    create_sub_agent = function(
      def,
      correlation = NULL,
      usage_limits = NULL,
      stateless = FALSE
    ) {
      begin_delegation_binding(self, def, correlation, stateless)
      bound <- FALSE
      on.exit(
        if (!bound) release_delegation_binding(self, correlation$delegation_id),
        add = TRUE
      )

      # Get the model to use. "inherit" clones the parent chat. A bare model
      # id (no "provider/" prefix) also clones it, keeping the lead's
      # provider, endpoint and credentials, and switches only the model: the
      # way to run a child on a cheaper model of a provider that
      # ellmer::chat() cannot name, such as a gateway client built outside
      # ellmer.
      same_provider <- def$model == "inherit" ||
        !grepl("/", def$model, fixed = TRUE)
      if (same_provider) {
        # Clone the parent chat to get the same provider/model config,
        # then clear conversation history so the sub-agent starts fresh.
        sub_chat <- tryCatch(
          {
            cloned <- clone_governed_chat(private$.chat)
            if (identical(cloned, private$.chat)) {
              cli_abort("Chat cloning must return an independent instance")
            }
            clear_chat_tool_callbacks(cloned, source = private$.chat)
            cloned$set_turns(list())
            # The child definition chooses its tools. Inherited provider
            # configuration must not import the parent's executable registry.
            cloned$set_tools(list())
            if (def$model != "inherit") {
              cloned$set_model(def$model)
            }
            cloned
          },
          error = function(e) {
            cli_abort(c(
              if (def$model == "inherit") {
                "Could not inherit model from parent for sub-agent {.val {def$name}}"
              } else {
                "Could not use model {.val {def$model}} on the parent's provider for sub-agent {.val {def$name}}"
              },
              "x" = e$message,
              "i" = "Please specify an explicit {.arg model} in {.fn agent_definition}"
            ))
          }
        )
      } else {
        # Use the specified model string (e.g., "openai/gpt-6-luna", "anthropic/claude-sonnet-5")
        sub_chat <- tryCatch(
          ellmer::chat(def$model),
          error = function(e) {
            cli_abort(c(
              "Failed to create chat for sub-agent {.val {def$name}}",
              "x" = "Invalid model: {.val {def$model}}",
              "i" = e$message
            ))
          }
        )
      }

      sub_tools <- private$filter_disallowed_tools(
        def$tools,
        def$disallowed_tools
      )
      sub_permissions <- private$derive_subagent_permissions(def)
      sub_prompt <- def$prompt
      if (!is.null(def$memory) && length(def$memory) > 0) {
        sub_prompt <- paste(
          sub_prompt,
          "",
          "# Memory",
          paste(as.character(def$memory), collapse = "\n\n"),
          sep = "\n"
        )
      }

      # Create the sub-agent
      child_run_context <- merge_run_context(
        correlation$run_context,
        list(role = def$name)
      )
      sub_agent <- Agent$new(
        chat = sub_chat,
        tools = sub_tools,
        system_prompt = sub_prompt,
        permissions = sub_permissions,
        usage_limits = usage_limits %||%
          private$derive_subagent_usage_limits(def),
        context_policy = self$context_policy,
        working_dir = self$working_dir,
        session_id = new_deputy_id("session_"),
        run_context = child_run_context,
        agent_name = def$name
      )
      sub_agent$.__enclos_env__$private$.parent_agent_id <-
        correlation$parent_agent_id
      sub_agent$.__enclos_env__$private$.parent_run_id <-
        correlation$parent_run_id
      sub_agent$.__enclos_env__$private$.delegation_id <-
        correlation$delegation_id
      # A checkpoint describes workspace state, not one agent's private
      # execution history. Delegated agents therefore write to the exact same
      # journal as the lead so a lead-level rewind includes child mutations.
      if (!stateless && !is.null(private$.file_checkpoints)) {
        sub_agent$.__enclos_env__$private$.file_checkpoints <-
          private$.file_checkpoints
      }
      # Load any skills
      for (skill in def$skills) {
        sub_agent$load_skill(skill)
      }

      bind_delegation_host(self, sub_agent, def, correlation, stateless)
      # Check the final registry, after binding has applied the denylist to
      # skill and host tools. A failure here still releases the binding.
      private$inherit_trusted_results(sub_agent)
      bound <- TRUE
      sub_agent
    },

    # The whole delegation tree obeys one no-bypass rule: the lead may keep its
    # own delegate tool only because every child inherits the policy.
    check_trusted_tools = function(tools) {
      policy <- private$.trusted_results
      if (is.null(policy)) {
        return(invisible(NULL))
      }
      # Designated producers must be declared statically, in tools or Skill
      # values. Skills named by path load fresh objects when each child is
      # built, so they may add other checked tools but never a producer.
      definitions <- lapply(private$.sub_agent_defs, function(def) {
        skill_tools <- unlist(
          lapply(def$skills, function(skill) {
            if (S7::S7_inherits(skill, Skill)) skill$tools else list()
          }),
          recursive = FALSE
        )
        validate_tool_batch(private$filter_disallowed_tools(
          c(def$tools, skill_tools),
          def$disallowed_tools
        ))
      })
      sources <- trusted_tree_sources(policy, c(list(tools), definitions))
      check_trusted_registry(
        policy,
        tools,
        available = unique(c(
          names(tools),
          unlist(lapply(definitions, names), use.names = FALSE)
        )),
        allow_delegation = TRUE,
        sources = sources
      )
      for (name in names(definitions)) {
        withCallingHandlers(
          check_trusted_registry(
            policy,
            definitions[[name]],
            available = policy@results,
            sources = sources
          ),
          deputy_tool_registration = function(error) {
            rlang::abort(
              paste0(
                "AgentDefinition '",
                name,
                "' violates the trusted-results policy."
              ),
              class = setdiff(
                class(error),
                c("rlang_error", "error", "condition")
              ),
              parent = error
            )
          }
        )
      }
      invisible(sources)
    },

    # Children inherit the lead policy. Their trusted results are recorded in
    # the lead's run and delivered to the lead's callback, with the child's
    # correlation fields intact.
    inherit_trusted_results = function(child) {
      policy <- private$.trusted_results
      if (is.null(policy)) {
        return(invisible(NULL))
      }
      sources <- private$check_trusted_tools(private$.chat$get_tools())
      forward <- function(event) {
        private$record_run_event(event)
        if (is.function(policy@on_result)) {
          policy@on_result(event)
        }
        invisible(NULL)
      }
      child_private <- child$.__enclos_env__$private
      child_private$.trusted_results <- do.call(
        TrustedResults,
        c(
          as.list(policy@results),
          list(
            on_result = forward,
            exempt_tools = policy@exempt_tools,
            model_receipt = policy@model_receipt
          )
        )
      )
      child_private$.trusted_tree_member <- TRUE
      child_private$.trusted_sources <- sources
      child_private$check_trusted_tools(child$get_tools())
      invisible(NULL)
    },

    derive_subagent_permissions = function(def) {
      existing <- self$permissions
      requested_mode <- def$permission_mode %||% existing$mode
      allowed_modes <- permission_mode_targets(existing$mode)
      if (!requested_mode %in% allowed_modes) {
        cli_abort(c(
          "Sub-agent permission mode cannot change under the lead policy",
          "x" = paste0(
            "Lead mode ",
            existing$mode,
            " cannot delegate with mode ",
            requested_mode,
            "."
          ),
          "i" = paste0(
            "Use mode ",
            existing$mode,
            ", then tighten the child with disallowed_tools or ",
            "max_requests."
          )
        ))
      }
      denylist <- unique(c(existing$tool_denylist, def$disallowed_tools))

      ceiling <- permission_capabilities_from(existing)
      capabilities <- if (identical(requested_mode, existing$mode)) {
        ceiling
      } else {
        intersect_permission_capabilities(
          ceiling,
          permission_mode_capabilities(requested_mode, self$working_dir)
        )
      }

      Permissions(
        mode = requested_mode,
        file_read = capabilities$file_read,
        file_write = capabilities$file_write,
        bash = capabilities$bash,
        r_code = capabilities$r_code,
        web = capabilities$web,
        install_packages = capabilities$install_packages,
        can_use_tool = existing$can_use_tool,
        tool_allowlist = existing$tool_allowlist,
        tool_denylist = denylist,
        permission_prompt_tool_name = capabilities$permission_prompt_tool_name
      )
    },

    prepare_cloned_tool = function(tool) {
      name <- read_optional_value(
        function() tool@name,
        validator = is_nonempty_string
      )
      if (
        identical(name$status, "present") &&
          identical(name$value, "delegate_to_agent")
      ) {
        return(private$adapt_tool(private$create_delegate_tool()))
      }
      private$adapt_tool(tool)
    },

    filter_disallowed_tools = function(tools, disallowed_tools) {
      if (is.null(disallowed_tools) || length(disallowed_tools) == 0) {
        return(tools)
      }

      disallowed <- tolower(trimws(as.character(disallowed_tools)))
      tool_names <- names(tools)
      keep <- vapply(
        seq_along(tools),
        function(index) {
          tool <- tools[[index]]
          label <- if (
            !is.null(tool_names) &&
              length(tool_names) >= index &&
              is_nonempty_string(tool_names[[index]])
          ) {
            tool_names[[index]]
          } else {
            paste0("#", index)
          }
          name <- read_optional_value(
            function() tool@name,
            validator = is_nonempty_string
          )

          if (identical(name$status, "unreadable")) {
            cli_warn(c(
              "Dropping tool {.val {label}} because its name could not be read.",
              "i" = "Tool object class: {.cls {class(tool)}}.",
              "x" = conditionMessage(name$error)
            ))
            return(FALSE)
          }

          if (!identical(name$status, "present")) {
            cli_warn(c(
              "Dropping tool {.val {label}} because it has no usable name.",
              "i" = "Tool object class: {.cls {class(tool)}}."
            ))
            return(FALSE)
          }

          !tolower(trimws(name$value)) %in% disallowed
        },
        logical(1)
      )

      tools[keep]
    },

    .sub_agent_defs = list(),
    .delegation_policy = NULL,
    delegation_sources = list()
  )
)
