# Agent class for deputy

#' Agent R6 Class
#'
#' @description
#' The main class for creating AI agents that can use tools to accomplish tasks.
#' Agent wraps an ellmer Chat object and adds agentic capabilities including
#' multi-turn execution, permission enforcement, and streaming output.
#'
#' **Security Note:** Core agent fields are read-only from the public API after
#' construction. Internal lifecycle methods may update the underlying state
#' through private storage when required.
#'
#' @section Skill Methods:
#' The following methods manage skills:
#'
#' \describe{
#'   \item{`$load_skill(skill, allow_conflicts = FALSE)`}{Load a [Skill] into
#'     the agent. The `skill` parameter can be a Skill object or path to a
#'     skill directory. If `allow_conflicts` is FALSE (default), an error is
#'     thrown when skill tools conflict with existing tools. Set to TRUE to
#'     allow overwriting. Returns invisible self.}
#'   \item{`$skills()`}{Get a named list of loaded [Skill] objects.}
#' }
#'
#' @section MCP Methods:
#' The following methods manage MCP (Model Context Protocol) server tools:
#'
#' \describe{
#'   \item{`$load_mcp(config = NULL, servers = NULL)`}{Load tools from MCP
#'     servers. The `config` parameter specifies the path to the MCP config
#'     file (defaults to `~/.config/mcptools/config.json`). The `servers`
#'     parameter optionally filters to specific server names. Requires the
#'     mcptools package. Returns invisible self.}
#'   \item{`$mcp_tools()`}{Get names of loaded MCP tools.}
#' }
#'
#' @section File checkpoint methods:
#' When `enable_file_checkpointing = TRUE`, Deputy captures exact preimages for
#' writes made through its native file tools.
#'
#' \describe{
#'   \item{`$checkpoint(name = NULL, metadata = list())`}{Create a manual file
#'     checkpoint and return its checkpoint ID.}
#'   \item{`$list_checkpoints()`}{List available file checkpoints.}
#'   \item{`$rewind_files(checkpoint_id)`}{Restore files to a checkpoint and
#'     invalidate later file history. Conversation history is not changed.}
#' }
#'
#' @include agent-stream.R agent-session.R agent-context.R agent-tool-callbacks.R agent-tool-records.R
#' @importFrom later run_now
#' @importFrom utils tail
#' @export
#'
#' @examples
#' \dontrun{
#' # Create an agent with file tools
#' agent <- Agent$new(
#'   chat = ellmer::chat("openai/gpt-5.6-luna"),
#'   tools = tools_file()
#' )
#'
#' # Run a task with streaming output
#' events <- agent$run("List files in the current directory")
#' repeat {
#'   event <- events()
#'   if (coro::is_exhausted(event)) break
#'   if (event$type == "text") cat(event$text)
#' }
#'
#' # Or use the blocking convenience method
#' result <- agent$run_sync("List files")
#' print(result$response)
#' }
Agent <- R6::R6Class(
  "Agent",

  public = list(
    #' @description
    #' Create a new Agent.
    #'
    #' @param chat An ellmer Chat object created by `ellmer::chat()` or
    #'   provider-specific functions like `ellmer::chat_openai()`.
    #' @param tools A list of tools created with `ellmer::tool()`. See
    #'   [tools_file()] and [tools_code()] for built-in tool bundles.
    #' @param system_prompt Optional system prompt. If provided, overrides the
    #'   chat object's existing system prompt.
    #' @param permissions A [Permissions] object controlling what the agent can do.
    #'   Defaults to [permissions_standard()].
    #' @param usage_limits [UsageLimits] applied independently to each run.
    #'   Defaults to 25 model requests. Use `UsageLimits()` for no limits.
    #' @param context_policy A [ContextPolicy] controlling automatic compaction
    #'   and durable offloading of large tool results.
    #' @param enable_file_checkpointing Whether to journal exact file preimages
    #'   for Deputy's mutating file tools. A checkpoint is created automatically
    #'   at the beginning of every run.
    #' @param file_checkpoint_max_file_bytes Maximum bytes captured for one
    #'   file preimage. Defaults to 50 MiB.
    #' @param file_checkpoint_max_journal_bytes Maximum aggregate serialized
    #'   bytes for checkpoint records, markers, metadata, and pending captures.
    #'   Defaults to 250 MiB.
    #' @param working_dir Working directory for file operations. Defaults to
    #'   current directory.
    #' @param session_id Optional stable session identifier used for correlation.
    #'   A unique identifier is generated by default.
    #' @param run_context Immutable canonical JSON-compatible product context
    #'   inherited by each run. Credential-like fields and runtime objects are
    #'   rejected.
    #' @param agent_id Optional stable identifier for this Agent instance.
    #'   A unique identifier is generated by default.
    #' @param agent_name Optional human-readable Agent name.
    #' @param fallback_chats Ordered configured ellmer Chats, explicitly allowed
    #'   to receive this conversation after a transient failure before any
    #'   response. Templates are cloned; their connection/model settings are
    #'   preserved and their history, system prompt, and tools are replaced by
    #'   the Agent's. The selected Chat remains active for subsequent runs.
    #'   Applies to governed task and structured requests. Pre-run automatic
    #'   compaction retains the separate [ContextPolicy] summary-failure policy.
    #' @return A new `Agent` object
    initialize = function(
      chat,
      tools = list(),
      system_prompt = NULL,
      permissions = NULL,
      usage_limits = UsageLimits(max_requests = 25),
      context_policy = ContextPolicy(),
      enable_file_checkpointing = FALSE,
      file_checkpoint_max_file_bytes = 50 * 1024^2,
      file_checkpoint_max_journal_bytes = 250 * 1024^2,
      working_dir = getwd(),
      session_id = NULL,
      run_context = list(),
      agent_id = NULL,
      agent_name = NULL,
      fallback_chats = list()
    ) {
      validate_chat(chat)
      private$.fallback_chats <- normalize_fallback_chats(fallback_chats, chat)

      agent_id <- validate_deputy_id(
        agent_id %||% new_deputy_id("agent_"),
        argument = "agent_id"
      )
      session_id <- validate_deputy_id(
        session_id %||% new_deputy_id("session_"),
        argument = "session_id"
      )
      if (
        !is.null(agent_name) &&
          (!is.character(agent_name) ||
            length(agent_name) != 1L ||
            is.na(agent_name) ||
            !nzchar(trimws(agent_name)))
      ) {
        cli_abort("{.arg agent_name} must be one non-empty string or NULL")
      }

      if (
        !is.character(working_dir) ||
          length(working_dir) != 1L ||
          is.na(working_dir) ||
          !dir.exists(working_dir)
      ) {
        cli_abort("{.arg working_dir} must be an existing directory")
      }
      working_dir <- normalizePath(working_dir, mustWork = TRUE, winslash = "/")

      private$.chat <- chat
      private$.permissions <- permissions %||% permissions_standard(working_dir)
      private$.usage_limits <- normalize_usage_limits(usage_limits)
      private$.context_policy <- normalize_context_policy(context_policy)
      private$.working_dir <- working_dir
      private$.hooks <- HookRegistry$new()
      private$.run_context <- normalize_run_context(run_context)
      private$.agent_id <- agent_id
      private$.agent_name <- agent_name
      private$.session_id <- session_id
      private$.file_checkpoint_config <- list(
        max_file_bytes = file_checkpoint_byte_limit(
          file_checkpoint_max_file_bytes,
          "file_checkpoint_max_file_bytes"
        ),
        max_journal_bytes = file_checkpoint_byte_limit(
          file_checkpoint_max_journal_bytes,
          "file_checkpoint_max_journal_bytes"
        )
      )
      if (
        !is.logical(enable_file_checkpointing) ||
          length(enable_file_checkpointing) != 1L ||
          is.na(enable_file_checkpointing)
      ) {
        cli_abort("{.arg enable_file_checkpointing} must be TRUE or FALSE")
      }
      if (isTRUE(enable_file_checkpointing)) {
        private$.file_checkpoints <- private$new_file_checkpoint_store()
      }

      # Override system prompt if provided
      if (!is.null(system_prompt)) {
        private$.chat$set_system_prompt(system_prompt)
      }

      # Rebind all tools to this Agent's runtime authority, including tools
      # configured on the supplied Chat before Agent construction.
      backend_tools <- private$.chat$get_tools()
      backend_tools <- validate_tool_batch(
        backend_tools,
        preserve_reader = TRUE
      )
      tools <- validate_tool_batch(tools, existing = backend_tools)
      wrapped <- lapply(c(backend_tools, tools), private$adapt_tool)
      private$.chat$set_tools(wrapped)

      # Wire up ellmer's callbacks for permission/hook enforcement
      private$.chat$on_tool_request(private$handle_tool_request)
      private$.chat$on_tool_result(private$handle_tool_result)

      # shinychat uses the ellmer Chat protocol structurally. Agent supplies
      # that protocol while retaining ownership of the wrapped backend.
      class(self) <- unique(c(class(self), "Chat"))
      private$.r6_clone <- self$clone
      rlang::env_binding_unlock(self, "clone")
      self$clone <- private$clone_client
      rlang::env_binding_lock(self, "clone")
      private$.compaction_catalog_registry <- new_compaction_catalog_registry(
        self
      )

      invisible(self)
    },

    #' @description
    #' Run an agentic task with semantic streaming events.
    #'
    #' Returns a generator that yields [AgentEvent] objects as the agent works.
    #' The agent will continue until the task is complete, a run limit is
    #' reached, or it is interrupted.
    #'
    #' @param task The task for the agent to perform
    #' @param usage_limits Optional [UsageLimits] override for this run.
    #' @param include_partial_messages If TRUE (default), yield partial text
    #'   chunks as they stream. If FALSE, only yield `text_complete`.
    #' @param run_context Canonical JSON-compatible context to add to or narrow
    #'   for this run. Protected constructor identity fields cannot change.
    #' @return A generator yielding [AgentEvent] objects
    #' @param type Optional ellmer type. Complete the task with tools, then
    #'   extract from the conversation within the same run budget.
    #' @param validate Optional synchronous function receiving ellmer's value.
    #'   Return TRUE, FALSE, or non-empty correction feedback. Errors and NA
    #'   are terminal.
    #' @param max_corrections Maximum additional structured requests after
    #'   invalid output. Defaults to zero; all attempts share the run budget.
    run = function(
      task,
      usage_limits = NULL,
      include_partial_messages = TRUE,
      run_context = list(),
      type = NULL,
      validate = NULL,
      max_corrections = 0L
    ) {
      structured <- structured_run_spec(type, validate, max_corrections)
      effective_run_context <- merge_run_context(
        private$.run_context,
        run_context
      )

      limits <- if (is.null(usage_limits)) {
        self$usage_limits
      } else {
        merge_usage_limits(usage_limits, self$usage_limits)
      }
      limits <- normalize_usage_limits(limits)

      governed_run <- private$start_governed_stream(
        messages = list(task),
        limits = limits,
        run_context = effective_run_context,
        stream = "content",
        extraction = structured
      )
      private$event_generator(
        governed_run,
        include_partial_messages = include_partial_messages
      )
    },

    #' @description
    #' Run an agentic task and block until completion.
    #'
    #' Convenience wrapper around `run()` that collects all events and returns
    #' an [AgentResult].
    #'
    #' @param task The task for the agent to perform
    #' @param usage_limits Optional [UsageLimits] override for this run.
    #' @param include_partial_messages If TRUE (default), keep partial text
    #'   events. If FALSE, suppress partials.
    #' @param run_context Canonical JSON-compatible context to add to or narrow
    #'   for this run. Protected constructor identity fields cannot change.
    #' @return An [AgentResult] object
    #' @param type Optional ellmer type. Complete the task with tools, then
    #'   extract from the conversation within the same run budget.
    #' @param validate Optional synchronous function receiving ellmer's value.
    #'   Return TRUE, FALSE, or non-empty correction feedback. Errors and NA
    #'   are terminal.
    #' @param max_corrections Maximum additional structured requests after
    #'   invalid output. Defaults to zero; all attempts share the run budget.
    run_sync = function(
      task,
      usage_limits = NULL,
      include_partial_messages = TRUE,
      run_context = list(),
      type = NULL,
      validate = NULL,
      max_corrections = 0L
    ) {
      gen <- self$run(
        task = task,
        usage_limits = usage_limits,
        include_partial_messages = include_partial_messages,
        run_context = run_context,
        type = type,
        validate = validate,
        max_corrections = max_corrections
      )
      repeat {
        event <- tryCatch(
          gen(),
          error = function(e) {
            if (
              grepl("generator has been exhausted", e$message, fixed = TRUE)
            ) {
              return(coro::exhausted())
            }
            stop(e)
          }
        )

        # Check for exhaustion (coro returns special exhausted symbol, not NULL)
        if (coro::is_exhausted(event)) {
          break
        }
      }

      result <- private$.last_run_result
      if (is.null(result)) {
        cli_abort("The governed run ended without an AgentResult")
      }
      result
    },

    #' @description
    #' Send messages synchronously using the ellmer Chat interface.
    #'
    #' All requests pass through Deputy's run kernel. The return value matches
    #' `ellmer::Chat$chat()`; inspect [AgentResult] metadata with `$last_run()`.
    #' @param ... User content accepted by ellmer.
    #' @param echo Accepted for ellmer compatibility.
    #' @param run_context Canonical JSON-compatible context to add to or narrow
    #'   for this run.
    #' @return The final assistant text.
    chat = function(..., echo = NULL, run_context = list()) {
      effective_run_context <- merge_run_context(
        private$.run_context,
        run_context
      )
      governed_run <- private$start_governed_stream(
        messages = list(...),
        limits = self$usage_limits,
        run_context = effective_run_context,
        stream = "content"
      )
      result <- private$resolve_promise(private$collect_governed_stream(
        governed_run
      ))
      private$echo_chat_result(result$response, echo)
      result$response
    },

    #' @description
    #' Send messages asynchronously using the ellmer Chat interface.
    #' @param ... User content accepted by ellmer.
    #' @param tool_mode Whether ellmer executes tool calls concurrently or
    #'   sequentially.
    #' @param run_context Canonical JSON-compatible context to add to or narrow
    #'   for this run.
    #' @return A promise resolving to the final assistant text.
    chat_async = function(
      ...,
      tool_mode = c("concurrent", "sequential"),
      run_context = list()
    ) {
      tool_mode <- match.arg(tool_mode)
      messages <- list(...)
      effective_run_context <- merge_run_context(
        private$.run_context,
        run_context
      )
      governed_run <- private$start_governed_stream(
        messages = messages,
        limits = self$usage_limits,
        run_context = effective_run_context,
        tool_mode = tool_mode,
        stream = "content"
      )
      private$collect_governed_stream(governed_run) |>
        promises::then(function(result) result$response)
    },

    #' @description Send a structured request through the governed run kernel.
    #' @param ... User content accepted by ellmer.
    #' @param type An ellmer structured-output type.
    #' @param echo Echo mode forwarded to ellmer.
    #' @param convert Whether ellmer converts the structured response.
    #' @param run_context Canonical JSON-compatible context to add to or narrow
    #'   for this run.
    #' @return Structured response data.
    #' @param validate Optional synchronous function receiving ellmer's value.
    #'   Return TRUE, FALSE, or non-empty correction feedback. Errors and NA
    #'   are terminal.
    #' @param max_corrections Maximum additional structured requests after
    #'   invalid output. Defaults to zero; all attempts share the run budget.
    chat_structured = function(
      ...,
      type,
      echo = "none",
      convert = TRUE,
      run_context = list(),
      validate = NULL,
      max_corrections = 0L
    ) {
      private$resolve_promise(self$chat_structured_async(
        ...,
        type = type,
        echo = echo,
        convert = convert,
        run_context = run_context,
        validate = validate,
        max_corrections = max_corrections
      ))
    },

    #' @description Send an asynchronous structured request through Deputy.
    #' @param ... User content accepted by ellmer.
    #' @param type An ellmer structured-output type.
    #' @param echo Echo mode forwarded to ellmer.
    #' @param convert Whether ellmer converts the structured response.
    #' @param run_context Canonical JSON-compatible context to add to or narrow
    #'   for this run.
    #' @return A promise resolving to structured response data.
    #' @param validate Optional synchronous function receiving ellmer's value.
    #'   Return TRUE, FALSE, or non-empty correction feedback. Errors and NA
    #'   are terminal.
    #' @param max_corrections Maximum additional structured requests after
    #'   invalid output. Defaults to zero; all attempts share the run budget.
    chat_structured_async = function(
      ...,
      type,
      echo = "none",
      convert = TRUE,
      run_context = list(),
      validate = NULL,
      max_corrections = 0L
    ) {
      effective_run_context <- merge_run_context(
        private$.run_context,
        run_context
      )
      governed_run <- private$start_governed_stream(
        messages = list(...),
        limits = self$usage_limits,
        run_context = effective_run_context,
        stream = "content",
        structured = structured_run_spec(
          type,
          validate,
          max_corrections,
          echo = echo,
          convert = convert
        )
      )
      private$collect_governed_stream(governed_run) |>
        promises::then(function(...) governed_run$state$structured_output)
    },

    #' @description
    #' Stream synchronously using the ellmer Chat interface.
    #' @param ... User content accepted by ellmer.
    #' @param stream Yield text or semantic ellmer content.
    #' @param controller Optional ellmer stream controller.
    #' @param run_context Canonical JSON-compatible context to add to or narrow
    #'   for this run.
    #' @return A synchronous generator.
    #' @param type Optional ellmer type for native structured streaming.
    #'   Providers requiring schema-tool fallback must use `chat_structured()`.
    stream = function(
      ...,
      stream = c("text", "content"),
      controller = NULL,
      run_context = list(),
      type = NULL
    ) {
      stream <- match.arg(stream)
      effective_run_context <- merge_run_context(
        private$.run_context,
        run_context
      )
      governed_run <- private$start_governed_stream(
        messages = list(...),
        limits = self$usage_limits,
        run_context = effective_run_context,
        stream = stream,
        controller = controller,
        stream_type = type
      )
      private$sync_stream_generator(governed_run$stream)
    },

    #' @description
    #' Stream asynchronously using the ellmer Chat interface.
    #'
    #' This is the primary interface for shinychat. It returns the same content
    #' stream as ellmer while enforcing Deputy permissions, hooks, limits,
    #' workspace resolution, context management, and run accounting.
    #' @param ... User content accepted by ellmer, including shinychat's list of
    #'   attachment-enabled `Content` objects.
    #' @param tool_mode Whether ellmer executes tool calls concurrently or
    #'   sequentially.
    #' @param stream Yield text or semantic ellmer content.
    #' @param controller Optional ellmer stream controller.
    #' @param run_context Canonical JSON-compatible context to add to or narrow
    #'   for this run.
    #' @return An asynchronous generator suitable for `shinychat::chat_append()`.
    #' @param type Optional ellmer type for native structured streaming.
    #'   Providers requiring schema-tool fallback must use `chat_structured()`.
    stream_async = function(
      ...,
      tool_mode = c("concurrent", "sequential"),
      stream = c("text", "content"),
      controller = NULL,
      run_context = list(),
      type = NULL
    ) {
      tool_mode <- match.arg(tool_mode)
      stream <- match.arg(stream)
      effective_run_context <- merge_run_context(
        private$.run_context,
        run_context
      )
      private$start_governed_stream(
        messages = list(...),
        limits = self$usage_limits,
        run_context = effective_run_context,
        tool_mode = tool_mode,
        stream = stream,
        controller = controller,
        stream_type = type
      )$stream
    },

    #' @description
    #' Return the most recently completed governed run.
    #' @return An [AgentResult], or `NULL` before the first run completes.
    last_run = function() {
      private$.last_run_result
    },

    #' @description Return the most recent compaction outcome.
    #' @return A `DeputyCompaction`, or `NULL` before compaction occurs.
    last_compaction = function() {
      private$.last_compaction
    },

    #' @description Resolve a durable tool-result reference.
    #' @param reference A `deputy://tool-result/...` URI or reference text
    #'   emitted into model context.
    #' @return The complete stored R value. Content evidence offloaded during
    #'   compaction uses its public text representation.
    #'   Compaction may retire superseded internal catalog URIs after installing
    #'   their replacement; saved sessions retain their catalog snapshots.
    resolve_tool_result = function(reference) {
      read_tool_result_envelope(
        reference,
        self$context_policy,
        private$.session_id
      )$value
    },

    #' @description Add a user/assistant turn pair, as in ellmer Chat.
    #' @param user User turn or content.
    #' @param assistant Assistant turn or content.
    #' @param log_tokens Whether ellmer should log token metadata.
    #' @return Invisible self.
    add_turn = function(user, assistant, log_tokens = TRUE) {
      private$.chat$add_turn(user, assistant, log_tokens = log_tokens)
      invisible(self)
    },

    #' @description Return conversation turns, as in ellmer Chat.
    #' @param include_system_prompt Include the system prompt as a turn.
    #' @return A list of ellmer turns.
    get_turns = function(include_system_prompt = FALSE) {
      if (
        "include_system_prompt" %in% names(formals(private$.chat$get_turns))
      ) {
        return(private$.chat$get_turns(
          include_system_prompt = include_system_prompt
        ))
      }
      private$.chat$get_turns()
    },

    #' @description Replace conversation turns, as in ellmer Chat. During a
    #'   run, already accrued usage remains charged after history replacement.
    #' @param value A list of ellmer turns.
    #' @return Invisible self.
    set_turns = function(value) {
      usage <- if (isTRUE(private$run_active)) private$current_run_usage()
      private$.chat$set_turns(value)
      preserve_run_usage(self, usage)
      prompt <- private$.chat$get_system_prompt()
      prompt_without_compaction <- private$system_prompt_without_compaction()
      if (!identical(prompt, prompt_without_compaction)) {
        private$.chat$set_system_prompt(prompt_without_compaction)
      }
      private$.compaction_summary <- NULL
      invisible(self)
    },

    #' @description Return the system prompt, as in ellmer Chat.
    #' @return The system prompt or `NULL`.
    get_system_prompt = function() {
      private$.chat$get_system_prompt()
    },

    #' @description Replace the system prompt, as in ellmer Chat.
    #' @param value The new system prompt or `NULL`.
    #' @return Invisible self.
    set_system_prompt = function(value) {
      previous_summary <- private$.compaction_summary
      private$.chat$set_system_prompt(value)
      private$appended_hook_context_hashes <- character()
      parts <- private$compaction_prompt_parts(value)
      private$.compaction_summary <- if (
        is.null(previous_summary) ||
          is.null(parts) ||
          !identical(parts$summary, previous_summary)
      ) {
        NULL
      } else {
        parts$summary
      }
      invisible(self)
    },

    #' @description Return registered tools, as in ellmer Chat.
    #' @return A named list of ellmer tool definitions.
    get_tools = function() {
      private$.chat$get_tools()
    },

    #' @description Replace registered tools, preserving Deputy adaptation.
    #' @param tools A list of ellmer tool definitions.
    #' @return Invisible self.
    set_tools = function(tools) {
      had_result_reader <- isTRUE(private$.tool_result_reader_registered)
      tools <- validate_tool_batch(tools, preserve_reader = TRUE)
      wrapped <- lapply(tools, private$adapt_tool)
      if (had_result_reader) {
        wrapped[["deputy_read_tool_result"]] <-
          private$.chat$get_tools()[["deputy_read_tool_result"]]
      }
      private$.chat$set_tools(wrapped)
      invisible(self)
    },

    #' @description Return provider token records, as in ellmer Chat.
    #' @param include_system_prompt Deprecated ellmer compatibility argument.
    #' @return A token data frame.
    get_tokens = function(include_system_prompt = NULL) {
      if (is.null(include_system_prompt)) {
        return(private$.chat$get_tokens())
      }
      private$.chat$get_tokens(include_system_prompt = include_system_prompt)
    },

    #' @description Return provider cost records, as in ellmer Chat.
    #' @param include Return all costs or only the latest request.
    #' @return Provider cost information.
    get_cost = function(include = c("all", "last")) {
      private$.chat$get_cost(include = match.arg(include))
    },

    #' @description Estimate tokens, as in ellmer Chat.
    #' @param ... User content accepted by ellmer.
    #' @param include Count only new content or the complete context.
    #' @param type Optional provider content type.
    #' @return Estimated token count.
    token_count = function(
      ...,
      include = c("new", "complete"),
      type = NULL
    ) {
      private$.chat$token_count(
        ...,
        include = match.arg(include),
        type = type
      )
    },

    #' @description Return the ellmer provider.
    #' @return An ellmer provider object.
    get_provider = function() {
      private$.chat$get_provider()
    },

    #' @description Return the configured model name.
    #' @return Model identifier.
    get_model = function() {
      private$.chat$get_model()
    },

    #' @description Return ellmer's configured model object.
    #' @return An ellmer model object, including parameters and extra arguments.
    get_model_object = function() {
      private$.chat$get_model_object()
    },

    #' @description Replace the configured model.
    #' @param model Model identifier.
    #' @return Invisible self.
    set_model = function(model) {
      private$.chat$set_model(model)
      invisible(self)
    },

    #' @description
    #' Register a tool with the agent.
    #'
    #' Function tools are wrapped with Deputy's runtime enforcement. Known
    #' provider-native web tools are authorized once, before registration,
    #' because their execution occurs inside the provider rather than R. Native
    #' tools therefore require static permissions and cannot be registered with
    #' a custom `can_use_tool` callback.
    #' Existing names require explicit replacement. Every tool in a batch is
    #' validated and adapted before the registry changes. List element names
    #' do not rename tools; each tool's own name is authoritative.
    #' @param tool A tool created with `ellmer::tool()` or a supported
    #'   provider-native web tool.
    #' @param replace Replace tools already registered under the same name?
    #'   Defaults to FALSE. Duplicate names within a batch always fail.
    #' @return Invisible self for chaining
    register_tool = function(tool, replace = FALSE) {
      self$register_tools(list(tool), replace = replace)
    },

    #' @description
    #' Register multiple tools with the agent.
    #'
    #' @param tools A list of function tools or supported provider-native web
    #'   tools.
    #' @param replace Replace tools already registered under the same name?
    #'   Defaults to FALSE. Duplicate names within a batch always fail.
    #' @return Invisible self for chaining
    register_tools = function(tools, replace = FALSE) {
      existing <- private$.chat$get_tools()
      tools <- validate_tool_batch(tools, existing, replace = replace)
      wrapped <- lapply(tools, private$adapt_tool)
      existing[names(wrapped)] <- wrapped
      private$.chat$set_tools(existing)
      invisible(self)
    },

    #' @description Register an additional ellmer tool-request observer.
    #' @param callback A function with one `request` argument.
    #' @return A function that removes the observer.
    on_tool_request = function(callback) {
      register_tool_observer(self, "request", callback)
    },

    #' @description Register an additional ellmer tool-result observer.
    #' @param callback A function with one `result` argument.
    #' @return A function that removes the observer.
    on_tool_result = function(callback) {
      register_tool_observer(self, "result", callback)
    },

    #' @description
    #' Add a hook to the agent.
    #'
    #' Hooks are called at specific points during agent execution and can
    #' modify behavior (e.g., deny tool calls, log events).
    #'
    #' @param hook A [HookMatcher] object
    #' @return Invisible self for chaining
    #'
    #' @examples
    #' \dontrun{
    #' # Add a hook to block dangerous bash commands
    #' agent$add_hook(hook_block_dangerous_bash())
    #'
    #' # Add a custom PreToolUse hook
    #' agent$add_hook(HookMatcher$new(
    #'   event = "PreToolUse",
    #'   pattern = "^write_file$",
    #'   callback = function(tool_name, tool_input, context) {
    #'     cli::cli_alert_info("Writing to: {tool_input$path}")
    #'     HookResultPreToolUse(permission = "allow")
    #'   }
    #' ))
    #' }
    add_hook = function(hook) {
      if (!inherits(hook, "HookMatcher")) {
        cli_abort("{.arg hook} must be a HookMatcher object")
      }
      self$hooks$add(hook)
      invisible(self)
    },

    #' @description
    #' Get the conversation history.
    #'
    #' @return A list of Turn objects
    turns = function() {
      private$.chat$get_turns()
    },

    #' @description
    #' Get the last turn in the conversation.
    #'
    #' @param role Role to filter by ("assistant", "user", or "system")
    #' @return A Turn object or NULL
    last_turn = function(role = c("assistant", "user", "system")) {
      private$.chat$last_turn(role = match.arg(role))
    },

    #' @description
    #' Get this agent's session identifier.
    #'
    #' @return Character session identifier
    session_id = function() {
      private$.session_id
    },

    #' @description
    #' Get the active permission mode.
    #'
    #' @return Character permission mode
    get_permission_mode = function() {
      self$permissions$mode
    },

    #' @description
    #' Preserve or narrow the active permission mode for subsequent tool calls.
    #' Reapplying the current mode is a no-op. Widening or incomparable mode
    #' changes require a newly configured `Agent` so custom restrictions remain
    #' an immutable authority ceiling. When narrowing removes web access,
    #' registered provider-native web tools are removed before the new policy
    #' becomes active because Deputy cannot interpose on provider-side calls.
    #'
    #' @param mode Permission mode, see [PermissionMode]
    #' @return Invisible self
    set_permission_mode = function(mode) {
      mode <- validate_permission_mode_value(mode)
      existing <- self$permissions
      old_mode <- existing$mode

      if (identical(mode, old_mode)) {
        return(invisible(self))
      }

      if (!mode %in% permission_mode_targets(old_mode)) {
        cli_abort(
          c(
            "Permission mode cannot widen or replace the current policy",
            "x" = paste0(
              "Mode ",
              old_mode,
              " cannot change to ",
              mode,
              "."
            ),
            "i" = paste0(
              "Create a new Agent with explicitly broader Permissions to ",
              "make this change."
            )
          ),
          class = c("deputy_permission_mode_widening", "deputy_error")
        )
      }

      capabilities <- intersect_permission_capabilities(
        permission_capabilities_from(existing),
        permission_mode_capabilities(mode, self$working_dir)
      )

      narrowed_permissions <- Permissions$new(
        mode = mode,
        file_read = capabilities$file_read,
        file_write = capabilities$file_write,
        bash = capabilities$bash,
        r_code = capabilities$r_code,
        web = capabilities$web,
        install_packages = capabilities$install_packages,
        can_use_tool = existing$can_use_tool,
        tool_allowlist = existing$tool_allowlist,
        tool_denylist = existing$tool_denylist,
        permission_prompt_tool_name = capabilities$permission_prompt_tool_name
      )

      registered_tools <- private$.chat$get_tools()
      provider_native <- vapply(
        registered_tools,
        inherits,
        logical(1),
        what = "ellmer::ToolBuiltIn"
      )
      removed_provider_tools <- character()
      if (!isTRUE(narrowed_permissions$web) && any(provider_native)) {
        removed_provider_tools <- vapply(
          registered_tools[provider_native],
          \(tool) tool@name,
          character(1)
        )
        private$.chat$set_tools(registered_tools[!provider_native])
      }

      private$.permissions <- narrowed_permissions

      private$fire_hook(
        "ConfigChange",
        key = "permission_mode",
        old_value = old_mode,
        new_value = mode,
        context = private$hook_context()
      )

      private$notify(
        paste0("Permission mode changed from ", old_mode, " to ", mode, "."),
        level = "info",
        code = "permission_mode_changed",
        previous_mode = old_mode,
        permission_mode = mode,
        removed_provider_tools = removed_provider_tools
      )

      invisible(self)
    },

    #' @description
    #' Get cost information for the conversation.
    #'
    #' @return A list with input, output, and cached token counts; total
    #'   estimated cost; and `complete` and `missing` fields describing provider
    #'   cost coverage. An incomplete total is `NA_real_`.
    cost = function() {
      summary <- provider_usage_summary(private$.chat)
      summary[c("input", "output", "cached", "total", "complete", "missing")]
    },

    #' @description
    #' Get normalized usage for the complete in-memory conversation.
    #'
    #' Per-run usage is available on [AgentResult] and in the final `usage`
    #' event returned by `$run()`.
    #'
    #' @return An [AgentUsage] object
    usage = function() {
      agent_usage_snapshot(private$.chat)
    },

    #' @description
    #' Request cancellation of the active stream.
    #'
    #' Cancellation is cooperative and takes effect at the next provider or tool
    #' boundary supported by ellmer.
    #'
    #' @param reason Stable reason stored on the terminal event
    #' @return Invisible logical indicating whether a run was active
    interrupt = function(reason = "interrupted") {
      if (!isTRUE(private$run_active)) {
        return(invisible(FALSE))
      }
      private$should_stop <- TRUE
      private$stop_reason_from_hook <- as.character(reason[[1]])
      controller <- private$current_stream_controller
      if (!is.null(controller)) {
        tryCatch(
          controller$cancel(reason = private$stop_reason_from_hook),
          error = function(e) controller$cancel()
        )
      }
      invisible(TRUE)
    },

    #' @description
    #' Get provider information.
    #'
    #' @return A list with provider name and model
    provider = function() {
      provider <- private$.chat$get_provider()
      list(
        name = provider@name,
        model = private$.chat$get_model()
      )
    },

    #' @description
    #' Save the current session to an RDS file.
    #'
    #' @param path Path to save the session
    #' @return Invisible path
    #'
    #' @details
    #' The session file contains:
    #' - Conversation turns
    #' - System prompt
    #' - The cumulative compaction summary
    #' - Portable copies of offloaded tool results
    #' - Effective run context
    #' - File checkpoint state, when enabled
    #' - Metadata (timestamp, version, provider info)
    save_session = function(path) {
      tryCatch(
        {
          session <- private$build_session_payload()
          saveRDS(session, path)
          cli_alert_success("Session saved to {.path {path}}")
          invisible(path)
        },
        error = function(e) {
          abort_session_save(
            c(
              "Failed to save session file",
              "x" = e$message
            ),
            path = path,
            parent = e
          )
        }
      )
    },

    #' @description
    #' Load a session from an RDS file.
    #'
    #' @param path Path to the session file
    #' @return Invisible self
    #'
    #' @details
    #' Tools, permissions, hooks, and the working directory are runtime policy
    #' and are never restored from a session file. Saved run context is
    #' validated before conversation state changes and merged with constructor
    #' context; protected identity conflicts fail the load. Compaction summaries
    #' and integrity-checked tool-result envelopes are restored as conversational
    #' state under the receiving Agent's session identity.
    load_session = function(path) {
      if (isTRUE(private$run_active)) {
        cli::cli_abort(
          "Cannot load session state while this agent has an active run",
          class = c("deputy_run_active", "deputy_error")
        )
      }
      # Validate file exists
      if (!file.exists(path)) {
        abort_session_load(
          "Session file not found: {.path {path}}",
          path = path
        )
      }

      # Load with error handling
      session <- tryCatch(
        readRDS(path),
        error = function(e) {
          abort_session_load(
            c(
              "Failed to load session file",
              "x" = e$message
            ),
            path = path,
            parent = e
          )
        }
      )

      private$restore_session_payload(
        session,
        source = path
      )
      cli_alert_success("Session loaded from {.path {path}}")
      invisible(self)
    },

    #' @description
    #' Create a reversible file checkpoint.
    #'
    #' @param name Optional checkpoint label.
    #' @param metadata Optional serializable metadata list.
    #' @return The checkpoint ID.
    checkpoint = function(name = NULL, metadata = list()) {
      store <- private$require_file_checkpoint_store()
      name <- name %||%
        paste0(
          "manual checkpoint ",
          format(Sys.time(), "%Y-%m-%d %H:%M:%S")
        )
      checkpoint_id <- store$checkpoint(name, metadata)
      private$notify(
        paste0("Created file checkpoint ", checkpoint_id, "."),
        level = "info",
        code = "file_checkpoint_created",
        checkpoint_id = checkpoint_id,
        checkpoint_name = name
      )
      checkpoint_id
    },

    #' @description
    #' List reversible file checkpoints.
    #'
    #' @return A data frame ordered from oldest to newest.
    list_checkpoints = function() {
      private$require_file_checkpoint_store()$list_checkpoints()
    },

    #' @description
    #' Rewind files to a checkpoint without changing conversation history.
    #'
    #' @param checkpoint_id ID returned by `$checkpoint()` or present in a
    #'   `file_checkpoint` run event.
    #' @return A list describing the restored checkpoint and change count.
    rewind_files = function(checkpoint_id) {
      if (isTRUE(private$run_active)) {
        cli::cli_abort(
          "Cannot rewind files while this agent has an active run",
          class = c("deputy_run_active", "deputy_error")
        )
      }
      result <- private$require_file_checkpoint_store()$rewind(checkpoint_id)
      private$notify(
        paste0(
          "Rewound ",
          result$restored_changes,
          " file change(s) to ",
          result$checkpoint_id,
          "."
        ),
        level = "info",
        code = "files_rewound",
        checkpoint_id = result$checkpoint_id,
        restored_changes = result$restored_changes
      )
      result
    },

    #' @description
    #' Compact the conversation history to reduce context size.
    #'
    #' This method uses the LLM to generate a meaningful summary of older
    #' conversation turns, then replaces them with the summary appended to
    #' the system prompt. This preserves important context while reducing
    #' token usage.
    #'
    #' @param keep_last Number of recent turns to retain. `NULL` chooses a
    #'   complete conversational boundary using the context policy's token
    #'   target.
    #' @param summary Optional custom summary to use instead of auto-generating.
    #'   If NULL, the LLM will generate a summary focusing on key decisions,
    #'   findings, files discussed, and task progress.
    #' @param fallback What to do when LLM summary generation fails.
    #' @param automatic Whether the run kernel triggered this compaction.
    #' @param estimated_tokens Optional pre-compaction token estimate.
    #' @return A `DeputyCompaction` describing the method and usage.
    #'
    #' @details
    #' The compaction process:
    #' 1. Fires the PreCompact hook (can cancel or provide custom summary)
    #' 2. If no custom summary, uses LLM to summarize compacted turns
    #' 3. Appends summary to system prompt under "Previous Conversation Summary"
    #' 4. Keeps only the most recent `keep_last` turns
    #'
    #' LLM summary-generation failures are errors by default. A deterministic
    #' truncated-text summary is used only when `fallback = "text"` is
    #' explicitly configured. The returned object records that degraded method.
    compact = function(
      keep_last = NULL,
      summary = NULL,
      fallback = self$context_policy$fallback,
      automatic = FALSE,
      estimated_tokens = NULL
    ) {
      if (isTRUE(private$run_active) && !isTRUE(automatic)) {
        cli::cli_abort(
          "Cannot compact conversation state while this agent has an active run",
          class = c("deputy_run_active", "deputy_error")
        )
      }
      plan <- private$prepare_compaction(
        keep_last,
        summary,
        fallback,
        automatic,
        estimated_tokens
      )
      if (!is.null(plan$result)) {
        return(plan$result)
      }
      artifacts <- private$begin_compaction_artifacts()
      on.exit(private$finish_compaction_artifacts(artifacts), add = TRUE)
      generated <- if (is.null(plan$summary)) {
        private$generate_compaction_summary(plan$turns_to_compact, fallback)
      } else {
        list(summary = plan$summary, method = plan$method, usage = AgentUsage())
      }
      private$install_compaction(
        plan,
        generated$summary,
        generated$method,
        generated$usage
      )
    },

    #' @description
    #' Print the agent configuration.
    print = function() {
      provider_info <- self$provider()
      tools <- private$.chat$get_tools()

      cat("<Agent>\n")
      cat("  agent_id:", self$agent_id, "\n")
      if (!is.null(self$agent_name)) {
        cat("  agent_name:", self$agent_name, "\n")
      }
      cat("  provider:", provider_info$name, "\n")
      cat("  model:", provider_info$model, "\n")
      cat("  tools:", length(tools), "registered\n")
      if (length(tools) > 0) {
        tool_names <- names(tools)
        if (length(tool_names) > 5) {
          tool_names <- c(tool_names[1:5], "...")
        }
        cat("    ", paste(tool_names, collapse = ", "), "\n")
      }
      cat("  working_dir:", self$working_dir, "\n")
      cat("  permissions:\n")
      cat("    mode:", self$permissions$mode, "\n")
      invisible(self)
    },

    #' @description
    #' Load a [Skill] into the agent.
    #'
    #' @param skill A [Skill] object or path to a skill directory.
    #' @param allow_conflicts If FALSE (default), error on tool name conflicts.
    #'   Set TRUE to allow overwriting existing tools.
    #' @return Invisible self for chaining.
    load_skill = function(skill, allow_conflicts = FALSE) {
      if (is.character(skill)) {
        # Load from path
        skill <- skill_load(skill)
      }

      if (!inherits(skill, "Skill")) {
        cli_abort(
          "{.arg skill} must be a Skill object or path to a skill directory"
        )
      }

      # Get current provider for validation
      current_provider <- tryCatch(
        {
          provider_info <- self$provider()
          # provider() returns a list with name and model
          provider_info$name
        },
        error = function(e) {
          # Log unexpected errors (not just "no provider configured")
          if (
            !grepl("no provider|not configured", e$message, ignore.case = TRUE)
          ) {
            cli_warn(c(
              "Could not determine provider for skill validation",
              "x" = e$message,
              "i" = "Provider compatibility check will be skipped"
            ))
          }
          NULL
        }
      )

      # Check requirements with provider
      req_check <- skill$check_requirements(current_provider)

      # Report missing packages
      if (length(req_check$missing) > 0) {
        cli_warn(c(
          "Loading skill with missing packages: {.val {skill$name}}",
          "x" = "Missing: {.val {req_check$missing}}"
        ))
      }

      # Report provider mismatch
      if (isTRUE(req_check$provider_mismatch)) {
        required <- paste(req_check$required_providers, collapse = ", ")
        cli_warn(c(
          "Skill {.val {skill$name}} may not work optimally with current provider",
          "i" = "Current provider: {.val {current_provider}}",
          "i" = "Skill requires: {.val {required}}",
          "!" = "Some features may not work as expected"
        ))
      }

      # Register tools with conflict detection
      if (length(skill$tools) > 0) {
        # Get current tool names to detect conflicts
        current_tools <- private$.chat$get_tools()
        current_tool_names <- names(current_tools)

        # Get names of tools being registered
        new_tool_names <- vapply(
          skill$tools,
          function(tool) tool@name,
          character(1)
        )

        # Check for conflicts
        conflicts <- new_tool_names[new_tool_names %in% current_tool_names]
        if (length(conflicts) > 0) {
          if (isTRUE(allow_conflicts)) {
            cli_warn(c(
              "Skill {.val {skill$name}} overwrites existing tool(s)",
              "!" = "Conflicting tools: {.val {conflicts}}",
              "i" = "Previous definitions will be replaced"
            ))
          } else {
            cli_abort(c(
              "Skill {.val {skill$name}} conflicts with existing tool(s)",
              "!" = "Conflicting tools: {.val {conflicts}}",
              "i" = "Use {.code allow_conflicts = TRUE} to overwrite existing tools"
            ))
          }
        }

        self$register_tools(skill$tools, replace = allow_conflicts)
      }

      # Append prompt to system prompt
      if (!is.null(skill$prompt) && nchar(skill$prompt) > 0) {
        current_prompt <- private$.chat$get_system_prompt() %||% ""
        new_prompt <- paste(
          current_prompt,
          "",
          paste0("# Skill: ", skill$name),
          skill$prompt,
          sep = "\n"
        )
        private$.chat$set_system_prompt(new_prompt)
      }

      # Store reference to loaded skill
      if (is.null(private$loaded_skills)) {
        private$loaded_skills <- list()
      }
      private$loaded_skills[[skill$name]] <- skill

      cli_alert_success("Loaded skill: {.val {skill$name}}")
      invisible(self)
    },

    #' @description
    #' Get loaded skills.
    #'
    #' @return Named list of loaded [Skill] objects.
    skills = function() {
      if (is.null(private$loaded_skills)) {
        return(list())
      }
      private$loaded_skills
    },

    #' @description
    #' Load tools from MCP (Model Context Protocol) servers.
    #'
    #' Requires the mcptools package. Issues a warning if not installed or if
    #' tool fetching fails.
    #'
    #' @param config Path to MCP configuration file. If NULL (default), uses
    #'   the mcptools default location (`~/.config/mcptools/config.json`).
    #' @param servers Optional character vector of server names to load from.
    #'   If NULL, loads from all configured servers.
    #' @param replace Refresh the selected servers' complete tool sets, removing
    #'   obsolete tools, and explicitly replace other matching names. On failure,
    #'   tools whose connections were invalidated are removed; working tools remain.
    #' @return Invisible self for chaining
    load_mcp = function(config = NULL, servers = NULL, replace = FALSE) {
      if (!rlang::is_bool(replace)) {
        tool_registration_error("{.arg replace} must be TRUE or FALSE.")
      }
      # mcptools closes old transports before replacement discovery/validation.
      # Clean up on errors and interrupts as well as normal returns, including
      # failures while publishing a successfully discovered batch.
      on.exit(private$discard_stale_mcp_tools(), add = TRUE)
      loaded <- load_mcp_tools_result(config, servers)
      mcp_tools_list <- loaded$tools
      loaded_at <- Sys.time()

      if (isTRUE(loaded$success)) {
        # Prepare the whole refreshed registry before publishing it. Successful
        # discovery can contain zero tools; working unrelated tools are retained.
        existing <- private$.chat$get_tools()
        removed <- character()
        tryCatch(
          {
            if (replace) {
              from_selected_server <- vapply(
                existing,
                function(tool) {
                  source <- tool_metadata(tool)$source
                  identical(source$type, "mcp") &&
                    source$server %in% loaded$servers
                },
                logical(1)
              )
              removed <- names(existing)[from_selected_server]
              retained <- existing[!from_selected_server]
              incoming <- validate_tool_batch(
                mcp_tools_list,
                retained,
                replace = TRUE
              )
              retained[names(incoming)] <- incoming
              self$set_tools(retained)
            } else {
              self$register_tools(mcp_tools_list)
            }
          },
          error = function(e) {
            private$loaded_mcp_status <- c(
              private$loaded_mcp_status,
              list(list(
                status = "failed",
                config = config,
                servers = loaded$servers,
                tools = character(),
                loaded_at = loaded_at,
                error = conditionMessage(e)
              ))
            )
            cli::cli_abort(c(
              "Failed to register MCP tools",
              "x" = e$message,
              "i" = "Check for tool name conflicts with existing tools"
            ))
          }
        )
        private$loaded_mcp_tools <- setdiff(private$loaded_mcp_tools, removed)
      }

      if (length(mcp_tools_list) > 0) {
        # Track loaded MCP tools with warnings for extraction failures
        tool_names <- vapply(
          seq_along(mcp_tools_list),
          function(i) {
            t <- mcp_tools_list[[i]]
            tryCatch(
              t@name %||% paste0("<unnamed_", i, ">"),
              error = function(e) {
                cli::cli_warn(c(
                  "Could not read name from MCP tool {.val {i}}",
                  "x" = e$message
                ))
                paste0("<unknown_", i, ">")
              }
            )
          },
          character(1)
        )
        private$loaded_mcp_tools <- unique(c(
          private$loaded_mcp_tools,
          tool_names
        ))
        private$loaded_mcp_status <- c(
          private$loaded_mcp_status,
          list(list(
            status = "connected",
            config = config,
            servers = servers %||% character(),
            tools = tool_names,
            loaded_at = loaded_at,
            error = NULL
          ))
        )
      } else {
        private$loaded_mcp_status <- c(
          private$loaded_mcp_status,
          list(list(
            status = if (!mcp_available()) {
              "unavailable"
            } else if (loaded$success) {
              "empty"
            } else {
              "failed"
            },
            config = config,
            servers = servers %||% character(),
            tools = character(),
            loaded_at = loaded_at,
            error = loaded$error
          ))
        )
      }

      invisible(self)
    },

    #' @description
    #' Get names of loaded MCP tools.
    #'
    #' @return Character vector of MCP tool names
    mcp_tools = function() {
      private$loaded_mcp_tools
    },

    #' @description
    #' Get MCP runtime status records.
    #'
    #' @return Data frame describing MCP load attempts and registered tools
    mcp_status = function() {
      records <- private$loaded_mcp_status
      if (length(records) == 0) {
        return(data.frame(
          status = character(),
          config = character(),
          servers = character(),
          tools = character(),
          loaded_at = as.POSIXct(character()),
          error = character(),
          stringsAsFactors = FALSE
        ))
      }

      do.call(
        rbind,
        lapply(records, function(record) {
          data.frame(
            status = record$status,
            config = record$config %||% NA_character_,
            servers = paste(record$servers, collapse = ","),
            tools = paste(record$tools, collapse = ","),
            loaded_at = as.POSIXct(record$loaded_at, tz = "UTC"),
            error = record$error %||% NA_character_,
            stringsAsFactors = FALSE
          )
        })
      )
    },

    #' @description
    #' Run an agentic task asynchronously and resolve to an [AgentResult].
    #'
    #' Uses the same run kernel as `$stream_async()`, `$stream()`, `$chat()`,
    #' and `$run_sync()`. It collects the final response and run metadata rather
    #' than returning the content stream.
    #'
    #' Use this when an Agent is a *worker* inside a larger async system, for
    #' example a delegated sub-agent executed from the tool of a parent chat
    #' that is itself streaming. Supply `type` to extract structured output
    #' after the tool-using task within the same run budget.
    #'
    #' @param task The task for the agent to perform
    #' @param usage_limits Optional [UsageLimits] override for this run. Unset
    #'   fields fall back to the Agent's limits. With `on_exceed = "error"`,
    #'   hitting a limit rejects the promise with the structured limit error
    #'   instead of resolving with a typed `stop_reason`.
    #' @param run_context Canonical JSON-compatible context to add to or narrow
    #'   for this run. Protected constructor identity fields cannot change.
    #' @return A `promises::promise` resolving to an [AgentResult]. It is
    #'   rejected if the provider stream fails or a limit configured with
    #'   `on_exceed = "error"` is reached.
    #' @param type Optional ellmer type. Complete the task with tools, then
    #'   extract from the conversation within the same run budget.
    #' @param validate Optional synchronous function receiving ellmer's value.
    #'   Return TRUE, FALSE, or non-empty correction feedback. Errors and NA
    #'   are terminal.
    #' @param max_corrections Maximum additional structured requests after
    #'   invalid output. Defaults to zero; all attempts share the run budget.
    run_async = function(
      task,
      usage_limits = NULL,
      run_context = list(),
      type = NULL,
      validate = NULL,
      max_corrections = 0L
    ) {
      structured <- structured_run_spec(type, validate, max_corrections)
      effective_run_context <- merge_run_context(
        private$.run_context,
        run_context
      )

      limits <- if (is.null(usage_limits)) {
        self$usage_limits
      } else {
        merge_usage_limits(usage_limits, self$usage_limits)
      }
      limits <- normalize_usage_limits(limits)

      governed_run <- private$start_governed_stream(
        messages = list(task),
        limits = limits,
        run_context = effective_run_context,
        stream = "content",
        extraction = structured
      )
      private$collect_governed_stream(governed_run)
    }
  ),
  active = list(
    #' @field agent_id Stable Agent instance identifier. Read-only.
    agent_id = function(value) {
      if (missing(value)) {
        return(private$.agent_id)
      }
      cli_abort("Cannot modify agent: agent_id is immutable after construction")
    },

    #' @field agent_name Optional human-readable Agent name. Read-only.
    agent_name = function(value) {
      if (missing(value)) {
        return(private$.agent_name)
      }
      cli_abort(
        "Cannot modify agent: agent_name is immutable after construction"
      )
    },

    #' @field run_context Default canonical product context. Read-only.
    run_context = function(value) {
      if (missing(value)) {
        return(clone_run_context(private$.run_context))
      }
      cli_abort(
        "Cannot modify agent: run_context is immutable after construction"
      )
    },

    #' @field permissions Permission policy for the agent. Read-only after construction.
    permissions = function(value) {
      if (missing(value)) {
        return(private$.permissions)
      }
      cli_abort(
        "Cannot modify agent: permissions are immutable after construction"
      )
    },

    #' @field usage_limits Default per-run [UsageLimits]. Read-only after construction.
    usage_limits = function(value) {
      if (missing(value)) {
        return(private$.usage_limits)
      }
      cli_abort(
        "Cannot modify agent: usage_limits are immutable after construction"
      )
    },

    #' @field context_policy Automatic context-management policy. Read-only.
    context_policy = function(value) {
      if (missing(value)) {
        return(normalize_context_policy(private$.context_policy))
      }
      cli_abort(
        "Cannot modify agent: context_policy is immutable after construction"
      )
    },

    #' @field working_dir Working directory for file operations. Read-only after construction.
    working_dir = function(value) {
      if (missing(value)) {
        return(private$.working_dir)
      }
      cli_abort(
        "Cannot modify agent: working_dir is immutable after construction"
      )
    },

    #' @field hooks Hook registry for lifecycle events. Read-only after construction.
    hooks = function(value) {
      if (missing(value)) {
        return(private$.hooks)
      }
      cli_abort("Cannot modify agent: hooks are immutable after construction")
    }
  ),

  private = c(
    list(
      .chat = NULL,
      .fallback_chats = list(),
      .fallback_position = 0L,
      .permissions = NULL,
      .usage_limits = NULL,
      .context_policy = NULL,
      .working_dir = NULL,
      .hooks = NULL,
      .run_context = list(),
      .agent_id = NULL,
      .agent_name = NULL,
      .session_id = NULL,
      .parent_agent_id = NULL,
      .parent_run_id = NULL,
      .delegation_id = NULL,
      .file_checkpoints = NULL,
      .file_checkpoint_config = NULL,

      # Flag to signal stopping from hooks
      should_stop = FALSE,
      stop_reason_from_hook = NULL,

      # Run-scoped tracing and usage state.
      run_active = FALSE,
      current_run_id = NULL,
      current_run_context = NULL,
      current_run_state = NULL,
      last_run_context = NULL,
      current_usage_limits = NULL,
      current_usage_baseline = NULL,
      current_tool_calls = 0L,
      current_tool_results = 0L,
      current_outer_requests = 0L,
      current_external_usage = NULL,
      current_stream_controller = NULL,
      current_stream_content = FALSE,
      pending_events = list(),
      tool_started_at = list(),
      tool_event_overrides = list(),
      tool_call_records = list(),
      pending_delegations = list(),
      original_tool_results = list(),
      last_run_usage = NULL,
      .last_run_result = NULL,
      last_limit_status = NULL,
      last_tool_cycle_signature = NULL,
      consecutive_tool_cycles = 0L,
      .last_compaction = NULL,
      .compaction_summary = NULL,
      .compaction_catalog_registry = NULL,
      .compaction_artifacts = NULL,
      .tool_result_reader_registered = FALSE,
      .tool_request_observers = list(),
      .tool_result_observers = list(),
      .tool_observer_id = 0L,
      .tool_observer_removers = list(),
      .r6_clone = NULL,
      current_run_checkpoint_id = NULL,

      clone_client = function(deep = FALSE) {
        invisible(deep)
        cloned <- private$.r6_clone(deep = TRUE)
        cloned$.__enclos_env__$private$rewire_chat_runtime()
        cloned$.__enclos_env__$private$.compaction_artifacts <- NULL
        register_compaction_catalog_owner(
          private$.compaction_catalog_registry,
          cloned
        )
        cloned
      },

      deep_clone = function(name, value) {
        if (identical(name, ".chat") && is.function(value$clone)) {
          return(clone_governed_chat(value))
        }
        is_r6_object <- is.environment(value) &&
          !is.null(get0(".__enclos_env__", value, inherits = FALSE))
        if (is_r6_object) {
          return(value$clone(deep = TRUE))
        }
        value
      },

      rewire_chat_runtime = function() {
        clear_chat_tool_callbacks(private$.chat)

        tools <- private$.chat$get_tools()
        had_result_reader <- "deputy_read_tool_result" %in% names(tools)
        tools[["deputy_read_tool_result"]] <- NULL
        tools <- validate_tool_batch(tools)
        private$.chat$set_tools(lapply(tools, private$prepare_cloned_tool))
        private$.tool_result_reader_registered <- FALSE
        if (isTRUE(had_result_reader)) {
          private$ensure_tool_result_reader()
        }
        private$.chat$on_tool_request(private$handle_tool_request)
        private$.chat$on_tool_result(private$handle_tool_result)
        rebind_tool_observers(self)
        invisible(NULL)
      },

      prepare_cloned_tool = function(tool) {
        private$adapt_tool(tool)
      },

      discard_stale_mcp_tools = function() {
        tools <- private$.chat$get_tools()
        current <- vapply(tools, mcp_tool_is_current, logical(1))
        if (all(current)) {
          return(invisible(NULL))
        }
        removed <- names(tools)[!current]
        # These are already adapted tools; only remove invalidated handles.
        private$.chat$set_tools(tools[current])
        private$loaded_mcp_tools <- setdiff(private$loaded_mcp_tools, removed)
        invisible(NULL)
      },

      new_file_checkpoint_store = function() {
        FileCheckpointStore$new(
          private$.working_dir,
          max_file_bytes = private$.file_checkpoint_config$max_file_bytes,
          max_journal_bytes = private$.file_checkpoint_config$max_journal_bytes
        )
      },

      resolve_tool_arguments = function(tool_name, arguments) {
        resolve_runtime_tool_arguments(
          tool_name,
          arguments,
          private$.working_dir
        )
      },

      adapt_tool = function(tool) {
        if (inherits(tool, "ellmer::ToolBuiltIn")) {
          tool_name <- tryCatch(tool@name, error = function(error) NULL)
          tool_id <- normalize_native_tool_id(tool_name %||% "")
          if (!tool_id %in% c("web_search", "web_fetch")) {
            cli_abort(c(
              "Unsupported provider-native tool: {.val {tool_name %||% '<unknown>'}}",
              "x" = paste0(
                "Deputy cannot interpose on provider-side execution for this ",
                "tool."
              )
            ))
          }
          if (!isTRUE(self$permissions$web)) {
            cli_abort(c(
              "Provider-native web tool {.val {tool_name}} is not authorized.",
              "i" = "Set {.code web = TRUE} and explicitly allow the tool."
            ))
          }
          allowlist <- self$permissions$tool_allowlist %||% character()
          allowlist_ids <- unique(vapply(
            allowlist,
            normalize_native_tool_id,
            character(1)
          ))
          if (!tool_id %in% allowlist_ids) {
            cli_abort(c(
              "Provider-native web tool {.val {tool_name}} is not explicitly allowed.",
              "i" = "Add the tool name to {.arg tool_allowlist}."
            ))
          }
          if (!is.null(self$permissions$can_use_tool)) {
            cli_abort(c(
              "Provider-native tool {.val {tool_name}} cannot use a custom permission callback.",
              "x" = paste0(
                "Provider-side requests cannot be checked against request ",
                "arguments or run context."
              ),
              "i" = paste0(
                "Remove {.arg can_use_tool} or use Deputy's universal ",
                "function tool."
              )
            ))
          }
          permission <- self$permissions$check(
            tool_name,
            list(),
            list(
              working_dir = private$.working_dir,
              tool_annotations = tool@annotations
            )
          )
          if (inherits(permission, "PermissionResultDeny")) {
            cli_abort(c(
              "Provider-native tool {.val {tool_name}} was denied at registration.",
              "x" = permission$reason,
              "i" = paste0(
                "Provider-native tools are authorized before a request because ",
                "they execute inside the provider."
              )
            ))
          }
          return(tool)
        }
        runtime_wrap_tool(
          tool,
          resolve_arguments = if (
            identical(tool_metadata(tool)$source$type, "mcp")
          ) {
            function(tool_name, arguments) arguments
          } else {
            private$resolve_tool_arguments
          },
          process_result = private$offload_tool_result,
          begin_execution = private$begin_tool_execution,
          execute = private$execute_tool
        )
      },

      execute_tool = function(tool, arguments) {
        workspace_runner <- attr(
          tool,
          "deputy_workspace_runner",
          exact = TRUE
        )
        if (is.function(workspace_runner)) {
          return(workspace_runner(arguments, private$.working_dir))
        }
        do.call(tool, arguments)
      },

      offload_tool_result = function(tool_name, value, execution_id = NULL) {
        if (identical(tool_name, "deputy_read_tool_result")) {
          return(value)
        }
        record <- offload_tool_result(
          value = value,
          tool_name = tool_name,
          policy = private$.context_policy,
          session_id = private$.session_id,
          agent_id = private$.agent_id
        )
        if (is.null(record)) {
          return(value)
        }
        # Returning a result to the caller claims it independently of any
        # concurrent compaction that first created these content-addressed bytes.
        private$.compaction_catalog_registry$provisional[[record$id]] <- NULL
        private$ensure_tool_result_reader()
        private$notify(
          paste0("Offloaded large result from ", tool_name, "."),
          level = "info",
          code = "tool_result_offloaded",
          tool_name = tool_name,
          result_reference = record$uri,
          result_bytes = record$bytes,
          result_sha256 = record$sha256
        )
        if (is_nonempty_string(execution_id)) {
          private$original_tool_results[[execution_id]] <- value
        }
        tool_result_reference_text(record)
      },

      ensure_tool_result_reader = function() {
        if (isTRUE(private$.tool_result_reader_registered)) {
          return(invisible(NULL))
        }
        private$.chat$register_tool(
          private$adapt_tool(tool_result_reader_tool(
            private$read_tool_result_chunk
          ))
        )
        private$.tool_result_reader_registered <- TRUE
        invisible(NULL)
      },

      read_tool_result_chunk = function(reference, offset, max_chars) {
        read_tool_result_chunk(
          reference = reference,
          offset = offset,
          max_chars = max_chars,
          policy = private$.context_policy,
          session_id = private$.session_id
        )
      },

      fire_hook = function(event, tool_name = NULL, ...) {
        if (length(self$hooks$get_hooks(event, tool_name))) {
          on.exit(
            private$record_run_event(private$agent_event("hook", hook = event)),
            add = TRUE
          )
        }
        self$hooks$fire(event, tool_name = tool_name, ...)
      },

      record_run_event = function(event) {
        state <- private$current_run_state
        if (!is.null(state)) {
          state$events[[length(state$events) + 1L]] <- event
          trace_governance_event(state$trace_span, event)
        }
        invisible(event)
      },

      # Track hashes of hook-supplied additional_context chunks already appended
      # to the system prompt so repeated hook returns don't grow it unboundedly.
      appended_hook_context_hashes = character(),

      notify = function(message, level = "info", code = NULL, ...) {
        private$fire_hook(
          "Notification",
          message = message,
          context = private$hook_context(
            level = level,
            code = code,
            ...
          )
        )
        invisible(NULL)
      },

      require_file_checkpoint_store = function() {
        if (is.null(private$.file_checkpoints)) {
          file_checkpoint_abort(c(
            "File checkpointing is not enabled for this agent.",
            "i" = "Create the agent with {.code enable_file_checkpointing = TRUE}."
          ))
        }
        private$.file_checkpoints
      },

      new_run_id = function() {
        new_deputy_id("run_")
      },

      active_run_id = function() {
        if (isTRUE(private$run_active)) {
          private$current_run_id
        } else {
          NULL
        }
      },

      effective_run_context = function() {
        clone_run_context(
          private$current_run_context %||% private$.run_context
        )
      },

      snapshot_run_context = function() {
        clone_run_context(
          private$current_run_context %||%
            private$last_run_context %||%
            private$.run_context
        )
      },

      event_correlation = function(delegation_id = NULL) {
        Filter(
          Negate(is.null),
          list(
            agent_id = private$.agent_id,
            agent_name = private$.agent_name,
            session_id = private$.session_id,
            run_id = private$active_run_id(),
            parent_agent_id = private$.parent_agent_id,
            parent_run_id = private$.parent_run_id,
            delegation_id = delegation_id %||% private$.delegation_id,
            run_context = private$effective_run_context()
          )
        )
      },

      agent_event = function(type, ..., delegation_id = NULL) {
        do.call(
          AgentEvent,
          c(
            list(type = type),
            private$event_correlation(delegation_id = delegation_id),
            list(...)
          )
        )
      },

      hook_context = function(..., delegation_id = NULL) {
        context <- utils::modifyList(
          list(working_dir = self$working_dir),
          list(...),
          keep.null = TRUE
        )
        correlation <- private$event_correlation(
          delegation_id = delegation_id
        )
        for (field in names(correlation)) {
          context[[field]] <- correlation[[field]]
        }
        context
      },

      current_run_usage = function() {
        baseline <- private$current_usage_baseline %||% AgentUsage()
        current <- agent_usage_snapshot(private$.chat)
        requests <- max(
          current$requests - baseline$requests,
          private$current_outer_requests
        )
        usage <- agent_usage_difference(
          current,
          baseline,
          tool_calls = private$current_tool_calls,
          requests = requests
        )
        agent_usage_add(
          usage,
          private$current_external_usage %||% AgentUsage()
        )
      },

      add_external_usage = function(usage) {
        if (!inherits(usage, "AgentUsage")) {
          return(invisible(FALSE))
        }
        private$current_external_usage <- agent_usage_add(
          private$current_external_usage %||% AgentUsage(),
          usage
        )
        if (!is.null(private$current_usage_limits)) {
          limit_status <- usage_limit_status(
            private$current_run_usage(),
            private$current_usage_limits,
            require_followup = TRUE
          )
          if (!is.null(limit_status)) {
            private$mark_usage_limit(limit_status)
          }
        }
        invisible(TRUE)
      },

      mark_usage_limit = function(status) {
        if (is.null(status)) {
          return(invisible(NULL))
        }
        if (is.null(private$last_limit_status)) {
          private$last_limit_status <- status
        }
        private$should_stop <- TRUE
        private$stop_reason_from_hook <- status$reason

        message <- usage_limit_message(status)
        private$notify(
          message,
          level = "warning",
          code = status$reason,
          usage = private$current_run_usage(),
          limit = status$limit
        )

        private$request_stream_stop(status$reason)
        invisible(status)
      },

      abort_usage_limit = function(status) {
        if (is.null(status)) {
          return(invisible(NULL))
        }
        message <- usage_limit_message(status)
        if (identical(status$reason, "request_limit")) {
          abort_request_limit(
            message,
            current_requests = status$actual,
            max_requests = status$limit,
            run_id = private$current_run_id
          )
        }
        if (identical(status$reason, "cost_unavailable")) {
          abort_cost_unavailable(
            message,
            max_cost = status$limit,
            run_id = private$current_run_id
          )
        }
        abort_budget_exceeded(
          message,
          current_cost = if (identical(status$reason, "cost_limit")) {
            status$actual
          } else {
            NULL
          },
          max_cost = if (identical(status$reason, "cost_limit")) {
            status$limit
          } else {
            NULL
          },
          budget_type = status$field,
          actual = status$actual,
          limit = status$limit,
          run_id = private$current_run_id
        )
      },

      append_hook_context = function(additional_context) {
        if (is.null(additional_context)) {
          return(invisible(NULL))
        }

        context_text <- paste(as.character(additional_context), collapse = "\n")
        if (!nzchar(trimws(context_text))) {
          return(invisible(NULL))
        }

        # De-duplicate by content hash. A hook that fires on every tool call
        # with the same context would otherwise grow the system prompt without
        # bound and inflate every subsequent persisted session payload.
        chunk_hash <- digest::digest(context_text, algo = "sha1")
        if (chunk_hash %in% private$appended_hook_context_hashes) {
          return(invisible(NULL))
        }
        private$appended_hook_context_hashes <- c(
          private$appended_hook_context_hashes,
          chunk_hash
        )

        current_prompt <- private$.chat$get_system_prompt() %||% ""
        private$.chat$set_system_prompt(paste(
          current_prompt,
          "",
          "# Hook Additional Context",
          context_text,
          sep = "\n"
        ))

        invisible(NULL)
      },

      # Create a true coro generator for streaming events

      get_last_response = function() {
        last <- private$.chat$last_turn()
        if (is.null(last)) {
          return(NULL)
        }
        last@text
      },

      # Storage for loaded skills
      loaded_skills = list(),

      # Storage for loaded MCP tool names
      loaded_mcp_tools = character(),
      loaded_mcp_status = list(),

      # Tool call counter for callback-based limits
      tool_call_count = 0L,

      # Active tool call limit; NULL means unbounded.
      tool_call_limit = NULL
    ),
    deputy_agent_stream_methods(),
    deputy_agent_session_methods(),
    deputy_agent_context_methods(),
    deputy_agent_tool_callbacks_methods(),
    deputy_agent_tool_records_methods()
  )
)
