#' @include agent-definition.R delegation-manifest.R delegation-binding.R delegation-inspection.R
NULL

# Multi-agent orchestration for deputy

deputy_lead_routing_start_marker <-
  "<!-- deputy-lead-routing:v1:start -->"
deputy_lead_routing_end_marker <-
  "<!-- deputy-lead-routing:v1:end -->"

#' LeadAgent R6 Class
#'
#' @description
#' A LeadAgent is an agent that can delegate tasks to specialized sub-agents.
#' It automatically has a `delegate_to_agent` tool that allows it to spawn
#' sub-agents based on registered AgentDefinitions.
#'
#' @export
LeadAgent <- R6::R6Class(
  "LeadAgent",
  inherit = Agent,

  public = list(
    #' @description
    #' Create a new LeadAgent.
    #'
    #' @param chat An ellmer Chat object
    #' @param sub_agents List of [agent_definition()] objects
    #' @param tools Additional tools for the lead agent
    #' @param system_prompt System prompt for the lead agent
    #' @param permissions Permissions for the lead agent (also applied to sub-agents)
    #' @param usage_limits Optional [UsageLimits] for each lead-agent run.
    #' @param context_policy A [ContextPolicy] controlling automatic compaction
    #'   and durable offloading of large tool results for the lead agent and its
    #'   delegated agents.
    #' @param enable_file_checkpointing Whether to journal reversible file
    #'   preimages in one workspace journal shared by the lead agent and its
    #'   delegated agents.
    #' @param file_checkpoint_max_file_bytes Maximum bytes captured for one
    #'   file preimage. Defaults to 50 MiB.
    #' @param file_checkpoint_max_journal_bytes Maximum aggregate serialized
    #'   bytes for workspace checkpoint records, markers, metadata, and pending
    #'   captures. Defaults to 250 MiB.
    #' @param working_dir Working directory
    #' @param session_id Optional stable session identifier used for correlation.
    #'   A unique identifier is generated by default.
    #' @param run_context Immutable canonical product context inherited by lead
    #'   runs and delegated agents.
    #' @param agent_id Optional stable identifier for this LeadAgent instance.
    #' @param agent_name Optional human-readable LeadAgent name.
    #' @param fallback_chats Ordered configured fallback Chats for the lead.
    #'   Child definitions inherit the selected provider, without an implicit
    #'   fallback policy of their own. See [Agent].
    #' @param delegation_sources Host-owned snapshot: unnamed list of up to 128
    #'   text records with `source_id`, `revision`, `owner_id`, `conversation_id`,
    #'   and `text`. Optional `allowed_agents` restricts definition names; `NULL`
    #'   allows all registered definitions, `character()` allows none. Each source
    #'   ID has one revision per scope. The host authenticates and authorizes
    #'   this snapshot; Deputy checks scope and exact revision, not live freshness.
    #' @param delegation_scope Plain list with `owner_id` and `conversation_id`;
    #'   required when sources are supplied. Model arguments cannot override it.
    #' @param delegation_policy Host-only [DelegationPolicy] for child governance,
    #'   resource ownership and interactive routing.
    #' @param delegation_disclosure Host-only [DelegationDisclosure] authorizing
    #'   inspection and saved-history disclosure. Defaults to deny.
    #' @param approval_dir Optional standalone lead approval directory. Delegation
    #'   rejects this unsupported durable child-continuation combination.
    #' @param delegation_max_bytes Positive finite admission ceiling, default
    #'   64 KiB, applied separately to the UTF-8 system/message text and serialized
    #'   complete manifest. Known complete-context estimates also obey
    #'   [ContextPolicy] `max_tokens`; unknown estimates remain `NULL` and rely
    #'   on byte bounds. Sources are text only, with a 16 MiB catalogue ceiling.
    #' @return A new `LeadAgent` object
    initialize = function(
      chat,
      sub_agents = list(),
      tools = list(),
      system_prompt = NULL,
      permissions = NULL,
      usage_limits = NULL,
      context_policy = ContextPolicy(),
      enable_file_checkpointing = FALSE,
      file_checkpoint_max_file_bytes = 50 * 1024^2,
      file_checkpoint_max_journal_bytes = 250 * 1024^2,
      working_dir = getwd(),
      session_id = NULL,
      run_context = list(),
      agent_id = NULL,
      agent_name = NULL,
      fallback_chats = list(),
      delegation_sources = list(),
      delegation_scope = list(),
      delegation_max_bytes = 65536L,
      delegation_policy = DelegationPolicy(),
      delegation_disclosure = DelegationDisclosure(),
      approval_dir = NULL
    ) {
      if (!S7::S7_inherits(delegation_policy, DelegationPolicy)) {
        delegation_binding_abort(
          "delegation_policy must be a DelegationPolicy."
        )
      }
      if (!S7::S7_inherits(delegation_disclosure, DelegationDisclosure)) {
        cli::cli_abort("delegation_disclosure must be a DelegationDisclosure.")
      }
      private$.delegation_disclosure <- delegation_disclosure
      private$.delegation_policy <- delegation_policy
      sources <- normalize_delegation_sources(
        delegation_sources,
        delegation_scope
      )
      private$delegation_sources <- sources$sources
      private$delegation_scope <- sources$scope
      private$delegation_max_bytes <- context_policy_whole_number(
        delegation_max_bytes,
        "delegation_max_bytes"
      )
      if (is.null(private$delegation_max_bytes)) {
        delegation_input_abort(
          "invalid",
          "delegation_max_bytes must be finite."
        )
      }
      private$.sub_agent_defs <- normalize_agent_definitions(sub_agents)

      # Build enhanced system prompt
      enhanced_prompt <- private$build_lead_prompt(
        system_prompt,
        private$.sub_agent_defs
      )

      # Create the delegate tool
      delegate_tool <- private$create_delegate_tool()

      # Combine tools
      all_tools <- c(list(delegate_tool), tools)

      # Call parent constructor
      super$initialize(
        chat = chat,
        tools = all_tools,
        system_prompt = enhanced_prompt,
        permissions = permissions,
        usage_limits = usage_limits,
        context_policy = context_policy,
        enable_file_checkpointing = enable_file_checkpointing,
        file_checkpoint_max_file_bytes = file_checkpoint_max_file_bytes,
        file_checkpoint_max_journal_bytes = file_checkpoint_max_journal_bytes,
        working_dir = working_dir,
        session_id = session_id,
        run_context = run_context,
        agent_id = agent_id,
        agent_name = agent_name,
        fallback_chats = fallback_chats,
        approval_dir = approval_dir
      )
    },

    #' @description
    #' Register a new sub-agent definition.
    #'
    #' @param definition An [agent_definition()] object
    #' @return Invisible self
    register_sub_agent = function(definition) {
      if (!S7::S7_inherits(definition, AgentDefinition)) {
        cli_abort("{.arg definition} must be an AgentDefinition object")
      }

      definition <- copy_agent_definition(definition)
      if (definition$name %in% names(private$.sub_agent_defs)) {
        cli_abort(
          "AgentDefinition {.val {definition$name}} is already registered"
        )
      }
      private$.sub_agent_defs[[definition$name]] <- definition

      # Replace only the generated routing section so compaction summaries,
      # skills, and hook-provided context remain intact.
      current_prompt <- private$.chat$get_system_prompt()
      new_prompt <- private$replace_lead_prompt(
        current_prompt,
        private$.sub_agent_defs
      )
      private$.chat$set_system_prompt(new_prompt)

      cli_alert_info("Registered sub-agent: {.val {definition$name}}")
      invisible(self)
    },

    #' @description
    #' Get available sub-agent names.
    #'
    #' @return Character vector of sub-agent names
    available_sub_agents = function() {
      unname(vapply(
        private$.sub_agent_defs,
        function(definition) definition$name,
        character(1)
      ))
    },

    #' @description
    #' Run independent, stateless responders concurrently.
    #'
    #' Each selected AgentDefinition gets a fresh conversation and at most one
    #' model request. Definitions with tools, skills, or MCP servers are
    #' rejected. This is tier-1 fan-out, not background tool-using agents.
    #' Results preserve input order, including failures and unstarted tasks.
    #' @param tasks A named character vector or named list of strings and
    #'   [DelegationInput] values. Names select unique registered AgentDefinitions.
    #' @param max_active Maximum simultaneous responders.
    #' @param mode Execution contract. Currently only `"stateless"` is supported.
    #' @param usage_limits Optional batch-wide [UsageLimits]. Unset fields
    #'   inherit the lead's defaults. Requests are reserved before dispatch;
    #'   token and cost ceilings are divided across each concurrent wave and
    #'   checked after responses, with possible overage by one response per
    #'   active responder.
    #' @param run_context Additional immutable context for the batch.
    #' @return A list with `mode`, named `results` ([AgentResult] or `NULL`),
    #'   named `outcomes` ([DelegationOutcome]), `errors`, `status`, and an
    #'   aggregate `run` ([AgentResult]).
    #'   `$last_run()` retains the aggregate run. The lead's conversation is
    #'   unchanged. Failed responders do not discard successful siblings.
    parallel_delegate = function(
      tasks,
      max_active = 2L,
      mode = "stateless",
      usage_limits = NULL,
      run_context = list()
    ) {
      promise <- self$parallel_delegate_async(
        tasks,
        max_active,
        mode,
        usage_limits,
        run_context
      )
      tryCatch(
        private$resolve_promise(promise),
        interrupt = function(condition) {
          self$interrupt()
          try(private$resolve_promise(promise), silent = TRUE)
          stop(condition)
        }
      )
    },

    #' @description
    #' Run stateless fan-out without blocking the R event loop.
    #' @param tasks,max_active,mode,usage_limits,run_context See
    #'   `$parallel_delegate()`.
    #' @return A promise resolving to the same batch result as
    #'   `$parallel_delegate()`. `$interrupt()` cancels queued work and asks
    #'   active responders to stop at their next supported provider boundary.
    parallel_delegate_async = function(
      tasks,
      max_active = 2L,
      mode = "stateless",
      usage_limits = NULL,
      run_context = list()
    ) {
      lead_parallel_delegate(
        self,
        tasks,
        max_active,
        mode,
        usage_limits,
        run_context
      )
    },

    #' @description
    #' Interrupt the lead and its active subagents cooperatively.
    #' @param reason Stable reason retained on stopped runs.
    #' @return Invisible logical indicating whether the lead or a Subagent was active.
    interrupt = function(reason = "interrupted") {
      active <- super$interrupt(reason)
      children <- private$active_subagents
      for (id in names(children)) {
        private$subagent_runs[[id]]$cancel_reason <- as.character(reason[[1L]])
        children[[id]]$interrupt(reason)
      }
      invisible(isTRUE(active) || length(children) > 0L)
    },

    #' @description
    #' List admitted subagent delegations in admission order, including live work.
    #' Status is `queued`, `running`, `completed`, `failed`, `stopped`,
    #' `not_started`, or `suspended` (for supported approval suspensions).
    #' `completed` means the run stopped with `complete`, not verified task success.
    #' `stop_reason` retains the exact runtime reason. Identifiers and timestamps
    #' are `NA` until assigned. `completed_at` marks settlement of this invocation,
    #' including suspension. `hook_error` records observer errors independently.
    #' `input_error` identifies preparation rejection as `invalid`, `missing`,
    #' `stale`, `unauthorized`, or `oversized`. These in-memory records are not
    #' durable jobs or a token event feed.
    #'
    #' @return Data frame with one row per admitted delegation
    list_subagents = function() {
      runs <- lead_delegation_records(self)
      if (length(runs) == 0) {
        return(data.frame(
          agent_name = character(),
          agent_id = character(),
          parent_agent_id = character(),
          session_id = character(),
          run_id = character(),
          parent_run_id = character(),
          delegation_id = character(),
          tool_call_id = character(),
          task = character(),
          status = character(),
          stop_reason = character(),
          input_error = character(),
          admitted_at = as.POSIXct(character()),
          hook_error = character(),
          cleanup_error = character(),
          started_at = as.POSIXct(character()),
          completed_at = as.POSIXct(character()),
          error = character(),
          stringsAsFactors = FALSE
        ))
      }

      do.call(
        rbind,
        lapply(runs, function(run) {
          data.frame(
            agent_name = run$agent_name,
            agent_id = run$agent_id %||% NA_character_,
            parent_agent_id = run$parent_agent_id %||% NA_character_,
            session_id = run$session_id %||% NA_character_,
            run_id = run$run_id %||% NA_character_,
            parent_run_id = run$parent_run_id %||% NA_character_,
            delegation_id = run$delegation_id %||% NA_character_,
            tool_call_id = run$tool_call_id %||% NA_character_,
            task = run$task,
            status = run$status,
            stop_reason = run$stop_reason %||% NA_character_,
            input_error = run$input_error %||% NA_character_,
            admitted_at = as.POSIXct(run$admitted_at, tz = "UTC"),
            hook_error = run$hook_error %||% NA_character_,
            cleanup_error = run$cleanup_error %||% NA_character_,
            started_at = as.POSIXct(run$started_at, tz = "UTC"),
            completed_at = as.POSIXct(run$completed_at, tz = "UTC"),
            error = run$error %||% NA_character_,
            stringsAsFactors = FALSE
          )
        })
      )
    },

    #' @description
    #' Get retained results from delegated sub-agent runs.
    #'
    #' @param agent_name Optional sub-agent name filter
    #' @param delegation_id Optional delegation identifier filter
    #' @return List of [AgentResult] objects in admission order, with `NULL` for
    #'   live, unstarted, or failed runs that did not return an AgentResult
    get_subagent_results = function(agent_name = NULL, delegation_id = NULL) {
      runs <- lead_delegation_records(self)
      if (!is.null(agent_name)) {
        runs <- Filter(
          function(run) identical(run$agent_name, agent_name),
          runs
        )
      }
      if (!is.null(delegation_id)) {
        runs <- Filter(
          function(run) identical(run$delegation_id, delegation_id),
          runs
        )
      }
      lapply(runs, function(run) run$agent_result)
    },

    #' @description
    #' Get current or retained conversation turns for admitted delegations.
    #' Live snapshots contain available turns, not every in-flight token.
    #' Reading history does not add it to the lead's model context. Hosts must
    #' authorize and redact disclosures before exposing these records to users.
    #'
    #' @param agent_name Optional sub-agent name filter
    #' @param session_id Optional sub-agent session id filter
    #' @return List of turn histories
    get_subagent_messages = function(agent_name = NULL, session_id = NULL) {
      runs <- lead_delegation_records(self, messages = TRUE)
      if (!is.null(agent_name)) {
        runs <- Filter(
          function(run) identical(run$agent_name, agent_name),
          runs
        )
      }
      if (!is.null(session_id)) {
        runs <- Filter(
          function(run) identical(run$session_id, session_id),
          runs
        )
      }

      lapply(runs, function(run) run$turns)
    },

    #' @description
    #' Inspect initial manifests or current model context in admission order.
    #' Initial manifests are immutable preparation receipts, separate from
    #' current working context and retained conversation turns. No provider
    #' requests or tool calls occur during inspection. Hosts authorize disclosure.
    #' @param delegation_id Optional exact delegation identifier.
    #' @param view `"initial"` for [DelegationManifest] values, `"current"` for
    #'   available system prompts and working turns.
    #' @param redact For initial manifests only, return an explicitly redacted
    #'   portable view omitting task, instructions and source text. Metadata still
    #'   requires host disclosure policy. The retained manifest is unchanged.
    #' @return A list; `NULL` entries mean no prepared context is available.
    #'   Current context is retained at settlement; no matches returns `list()`.
    get_subagent_contexts = function(
      delegation_id = NULL,
      view = "initial",
      redact = FALSE
    ) {
      lead_subagent_contexts(self, delegation_id, view, redact)
    },

    #' @description
    #' Inspect authorized child snapshots without executing or changing context.
    #' Runtime facts, model claims, per-run usage, retained transcript and initial
    #' manifest are separate. Cumulative child usage currently equals per-run
    #' usage because child continuation is unsupported. Unknown usage is NULL.
    #' @param requester Host-authenticated request context, never model arguments.
    #' @param delegation_id Optional exact delegation locator, checked only after
    #'   disclosure authorization. Unknown IDs return an empty list.
    #' @param transcript Include public ellmer content records and replayed
    #'   `turns`. Hidden thinking, provider JSON and display closures are omitted.
    #' @return Authorized and redacted read-only view lists. These are snapshots;
    #'   modifying a returned list never changes the child or lead context.
    inspect_subagents = function(
      requester,
      delegation_id = NULL,
      transcript = FALSE
    ) {
      views <- lead_inspect_subagents(
        self,
        requester,
        delegation_id,
        transcript
      )
      views <- lapply(views, function(view) {
        if (transcript) {
          view$turns <- lapply(view$transcript, inspection_replay)
        }
        view
      })
      inspection_bound(views, private$.delegation_disclosure)
    },

    #' @description
    #' Export authorized settled child history for host-owned durable storage.
    #' This is observation history, not a resumable Agent/session snapshot.
    #' @param requester,delegation_id See `$inspect_subagents()`.
    #' @return Portable versioned list for [delegation_history()]. Export rejects
    #'   active selected children. The host supplies current disclosure policy
    #'   when reading it back. Only public ellmer records are retained.
    export_subagents = function(requester, delegation_id = NULL) {
      views <- lead_inspect_subagents(
        self,
        requester,
        delegation_id,
        TRUE,
        settled_only = TRUE
      )
      inspection_bound(
        list(
          schema_version = 1L,
          settled = TRUE,
          scope = inspection_scope(self),
          children = views
        ),
        private$.delegation_disclosure
      )
    },

    #' @description
    #' Read an authorized retained delegation-answer artifact.
    #' @param requester,delegation_id See `$inspect_subagents()`.
    #' @param reference An exact reference included in the redacted authorized
    #'   child view. Missing or expired artifacts fail explicitly.
    #' @param offset Character offset for a bounded chunk, starting at zero.
    #' @return Existing bounded tool-result chunk; no tool or model executes.
    read_subagent_result = function(
      requester,
      delegation_id,
      reference,
      offset = 0L
    ) {
      views <- lead_inspect_subagents(self, requester, delegation_id, FALSE)
      references <- unlist(
        lapply(views, function(view) view$outcome$references),
        recursive = FALSE
      )
      selected <- Filter(
        function(ref) identical(ref$reference, reference),
        references
      )
      if (
        !is.character(reference) ||
          length(reference) != 1L ||
          is.na(reference) ||
          !length(selected)
      ) {
        delegation_disclosure_abort()
      }
      # Disclosure authorizes the public reference. Storage routing remains
      # host-owned even when the redactor removes or replaces private metadata.
      stored <- Filter(
        function(ref) identical(ref$reference, reference),
        unlist(
          lapply(
            Filter(
              function(record) identical(record$delegation_id, delegation_id),
              lead_delegation_records(self)
            ),
            function(record) record$references
          ),
          recursive = FALSE
        )
      )
      if (!length(stored)) {
        delegation_disclosure_abort()
      }
      chunk <- read_tool_result_chunk(
        reference,
        offset = offset,
        max_chars = 8192L,
        policy = self$context_policy,
        session_id = stored[[1L]]$storage_session_id
      )
      view <- private$.delegation_disclosure$redact(
        list(kind = "artifact", reference = reference, result = chunk),
        requester
      )
      inspection_portable(view)
      inspection_bound(view, private$.delegation_disclosure)
    },

    #' @description
    #' Print the lead agent.
    print = function() {
      super$print()
      cli::cat_line(cli::cli_format_method({
        cli::cli_div(theme = list(div = list("margin-left" = 2)))
        cli::cli_text("sub_agents: {length(private$.sub_agent_defs)}")
        if (length(private$.sub_agent_defs) > 0) {
          names <- self$available_sub_agents()
          cli::cli_text("{paste(names, collapse = \", \")}")
        }
      }))
      invisible(self)
    }
  ),

  active = list(
    #' @field sub_agent_defs Read-only snapshot of registered AgentDefinitions.
    sub_agent_defs = function(value) {
      if (!missing(value)) {
        cli_abort("{.field sub_agent_defs} is read-only")
      }
      unname(lapply(private$.sub_agent_defs, copy_agent_definition))
    }
  ),

  private = list(
    # Build the lead agent's system prompt
    build_lead_prompt = function(base_prompt, sub_agents) {
      lines <- character()

      if (!is.null(base_prompt)) {
        lines <- c(lines, base_prompt, "")
      }

      if (length(sub_agents) > 0) {
        lines <- c(
          lines,
          deputy_lead_routing_start_marker,
          "# Available Sub-Agents",
          "",
          "You can delegate specialized tasks to these sub-agents using the",
          "`delegate_to_agent` tool:",
          ""
        )

        for (def in sub_agents) {
          lines <- c(lines, paste0("## ", def$name), def$description, "")
        }

        lines <- c(
          lines,
          "When delegating, provide a clear task description. The sub-agent",
          "will complete the task and return results to you.",
          "",
          "# End Available Sub-Agents",
          deputy_lead_routing_end_marker,
          ""
        )
      }

      paste(lines, collapse = "\n")
    },

    replace_lead_prompt = function(full_prompt, sub_agents) {
      section <- private$build_lead_prompt(NULL, sub_agents)
      if (!is_nonempty_string(full_prompt)) {
        return(section)
      }

      start_marker <- deputy_lead_routing_start_marker
      end_marker <- deputy_lead_routing_end_marker
      start <- regexpr(start_marker, full_prompt, fixed = TRUE)
      if (start[[1L]] < 0L) {
        return(private$build_lead_prompt(full_prompt, sub_agents))
      }
      remainder <- substr(full_prompt, start[[1L]], nchar(full_prompt))
      end <- regexpr(end_marker, remainder, fixed = TRUE)
      if (end[[1L]] < 0L) {
        return(private$build_lead_prompt(full_prompt, sub_agents))
      }

      before <- substr(full_prompt, 1L, start[[1L]] - 1L)
      after_start <- start[[1L]] + end[[1L]] - 1L + attr(end, "match.length")
      after <- if (after_start > nchar(full_prompt)) {
        ""
      } else {
        substr(full_prompt, after_start, nchar(full_prompt))
      }
      paste0(before, section, after)
    },

    # Create the delegate_to_agent tool
    create_delegate_tool = function() {
      # Capture self for the closure
      lead_agent <- self

      ellmer::tool(
        fun = function(
          agent_name,
          task,
          constraints = character(),
          evidence = list(),
          deliverable = NULL,
          stop_conditions = character()
        ) {
          correlation <- private$claim_delegation()

          route_key <- if (is_nonempty_string(agent_name)) {
            tolower(trimws(agent_name))
          } else {
            ""
          }
          def <- private$.sub_agent_defs[[route_key]]

          if (is.null(def)) {
            available <- lead_agent$available_sub_agents()
            ellmer::tool_reject(paste0(
              "Unknown agent: ",
              agent_name,
              ". ",
              "Available agents: ",
              paste(available, collapse = ", ")
            ))
          }

          id <- lead_admit_delegation(lead_agent, def, task, correlation)
          child <- tryCatch(
            {
              input <- if (S7::S7_inherits(task, DelegationInput)) {
                if (
                  length(constraints) ||
                    length(evidence) ||
                    !is.null(deliverable) ||
                    length(stop_conditions)
                ) {
                  delegation_input_abort(
                    "invalid",
                    "Structured task cannot be combined with separate brief fields."
                  )
                }
                normalize_delegation_input(task)
              } else {
                DelegationInput(
                  task,
                  constraints,
                  delegation_tool_references(evidence),
                  deliverable,
                  stop_conditions
                )
              }
              prepared <- resolve_delegation_input(lead_agent, def, input)
              limits <- private$derive_subagent_usage_limits(def)
              child <- private$create_sub_agent(def, correlation, limits)
              manifest <- prepare_delegation_manifest(
                lead_agent,
                def,
                prepared,
                child
              )
              lead_bind_delegation(lead_agent, id, child, manifest)
              child
            },
            error = function(condition) {
              lead_settle_delegation(
                lead_agent,
                id,
                error = condition,
                stop_reason = "setup_error"
              )
              release_delegation_binding(lead_agent, id)
              stop(condition)
            }
          )
          # Reserve before returning the promise, so concurrent calls cannot
          # each receive the same remaining budget.
          private$reserve_delegation_usage(id, limits)
          cli::cli_alert_info("Delegating to {.val {def$name}}: {input$task}")
          lead_run_delegation(lead_agent, id, child, def, manifest$message) |>
            promises::then(function(outcome) {
              if (!is.null(private$current_usage_limits)) {
                limit <- usage_limit_status(
                  private$current_run_usage(),
                  private$current_usage_limits,
                  require_followup = TRUE
                )
                if (!is.null(limit)) private$mark_usage_limit(limit)
              }
              payload <- delegation_json(S7::props(delegation_outcome(
                private$subagent_runs[[id]],
                compact = TRUE
              )))
              if (!is.null(outcome$error)) {
                # The bounded payload already contains the label and error.
                ellmer::tool_reject(paste0("Subagent failed.\n", payload))
              }
              payload
            })
        },
        name = "delegate_to_agent",
        description = "Delegate a task to a specialized sub-agent. The sub-agent will complete the task and return results.",
        arguments = list(
          agent_name = ellmer::type_string(
            "Name of the sub-agent to delegate to"
          ),
          task = ellmer::type_string("The task to delegate to the Subagent"),
          constraints = ellmer::type_array(
            ellmer::type_string(),
            required = FALSE
          ),
          evidence = ellmer::type_array(
            ellmer::type_object(
              source_id = ellmer::type_string(),
              revision = ellmer::type_string()
            ),
            required = FALSE
          ),
          deliverable = ellmer::type_string(required = FALSE),
          stop_conditions = ellmer::type_array(
            ellmer::type_string(),
            required = FALSE
          )
        ),
        annotations = ellmer::tool_annotations(
          read_only_hint = FALSE,
          destructive_hint = FALSE,
          open_world_hint = FALSE,
          idempotent_hint = FALSE
        )
      )
    },

    # Create a sub-agent from a definition
    create_sub_agent = function(
      def,
      correlation = NULL,
      usage_limits = NULL,
      stateless = FALSE
    ) {
      begin_delegation_binding(self, def, correlation, stateless)
      bound <- FALSE
      on.exit(
        if (!bound) release_delegation_binding(self, correlation$delegation_id),
        add = TRUE
      )

      # Get the model to use
      if (def$model == "inherit") {
        # Clone the parent chat to get the same provider/model config,
        # then clear conversation history so the sub-agent starts fresh.
        sub_chat <- tryCatch(
          {
            cloned <- clone_governed_chat(private$.chat)
            if (identical(cloned, private$.chat)) {
              cli_abort("Chat cloning must return an independent instance")
            }
            clear_chat_tool_callbacks(cloned, source = private$.chat)
            cloned$set_turns(list())
            # The child definition chooses its tools. Inherited provider
            # configuration must not import the parent's executable registry.
            cloned$set_tools(list())
            cloned
          },
          error = function(e) {
            cli_abort(c(
              "Could not inherit model from parent for sub-agent {.val {def$name}}",
              "x" = e$message,
              "i" = "Please specify an explicit {.arg model} in {.fn agent_definition}"
            ))
          }
        )
      } else {
        # Use the specified model string (e.g., "openai/gpt-4o", "anthropic/claude-sonnet-4-5-20250929")
        sub_chat <- tryCatch(
          ellmer::chat(def$model),
          error = function(e) {
            cli_abort(c(
              "Failed to create chat for sub-agent {.val {def$name}}",
              "x" = "Invalid model: {.val {def$model}}",
              "i" = e$message
            ))
          }
        )
      }

      sub_tools <- private$filter_disallowed_tools(
        def$tools,
        def$disallowed_tools
      )
      sub_permissions <- private$derive_subagent_permissions(def)
      sub_prompt <- def$prompt
      if (!is.null(def$memory) && length(def$memory) > 0) {
        sub_prompt <- paste(
          sub_prompt,
          "",
          "# Memory",
          paste(as.character(def$memory), collapse = "\n\n"),
          sep = "\n"
        )
      }

      # Create the sub-agent
      child_run_context <- merge_run_context(
        correlation$run_context,
        list(role = def$name)
      )
      sub_agent <- Agent$new(
        chat = sub_chat,
        tools = sub_tools,
        system_prompt = sub_prompt,
        permissions = sub_permissions,
        usage_limits = usage_limits %||%
          private$derive_subagent_usage_limits(def),
        context_policy = self$context_policy,
        working_dir = self$working_dir,
        session_id = new_deputy_id("session_"),
        run_context = child_run_context,
        agent_name = def$name
      )
      sub_agent$.__enclos_env__$private$.parent_agent_id <-
        correlation$parent_agent_id
      sub_agent$.__enclos_env__$private$.parent_run_id <-
        correlation$parent_run_id
      sub_agent$.__enclos_env__$private$.delegation_id <-
        correlation$delegation_id
      # A checkpoint describes workspace state, not one agent's private
      # execution history. Delegated agents therefore write to the exact same
      # journal as the lead so a lead-level rewind includes child mutations.
      if (!stateless && !is.null(private$.file_checkpoints)) {
        sub_agent$.__enclos_env__$private$.file_checkpoints <-
          private$.file_checkpoints
      }
      # Load any skills
      for (skill in def$skills) {
        sub_agent$load_skill(skill)
      }

      bind_delegation_host(self, sub_agent, def, correlation, stateless)
      bound <- TRUE
      sub_agent
    },

    derive_subagent_permissions = function(def) {
      existing <- self$permissions
      requested_mode <- def$permission_mode %||% existing$mode
      allowed_modes <- permission_mode_targets(existing$mode)
      if (!requested_mode %in% allowed_modes) {
        cli_abort(c(
          "Sub-agent permission mode cannot change under the lead policy",
          "x" = paste0(
            "Lead mode ",
            existing$mode,
            " cannot delegate with mode ",
            requested_mode,
            "."
          ),
          "i" = paste0(
            "Use mode ",
            existing$mode,
            ", then tighten the child with disallowed_tools or ",
            "max_requests."
          )
        ))
      }
      denylist <- unique(c(existing$tool_denylist, def$disallowed_tools))

      ceiling <- permission_capabilities_from(existing)
      capabilities <- if (identical(requested_mode, existing$mode)) {
        ceiling
      } else {
        intersect_permission_capabilities(
          ceiling,
          permission_mode_capabilities(requested_mode, self$working_dir)
        )
      }

      Permissions(
        mode = requested_mode,
        file_read = capabilities$file_read,
        file_write = capabilities$file_write,
        bash = capabilities$bash,
        r_code = capabilities$r_code,
        web = capabilities$web,
        install_packages = capabilities$install_packages,
        can_use_tool = existing$can_use_tool,
        tool_allowlist = existing$tool_allowlist,
        tool_denylist = denylist,
        permission_prompt_tool_name = capabilities$permission_prompt_tool_name
      )
    },

    derive_subagent_usage_limits = function(def) {
      limits <- private$current_usage_limits %||% self$usage_limits
      current <- if (isTRUE(private$run_active)) {
        private$current_run_usage()
      } else {
        AgentUsage()
      }
      usage_fields <- c(
        max_requests = "requests",
        max_tool_calls = "tool_calls",
        max_input_tokens = "input_tokens",
        max_output_tokens = "output_tokens",
        max_total_tokens = "total_tokens",
        max_cost_usd = "cost_usd"
      )
      reserved <- private$reserved_delegation_usage()
      remaining <- lapply(names(usage_fields), function(limit_field) {
        limit <- S7::prop(limits, limit_field)
        if (is.null(limit)) {
          return(NULL)
        }
        max(
          0,
          limit -
            S7::prop(current, usage_fields[[limit_field]]) -
            reserved[[limit_field]]
        )
      })
      names(remaining) <- names(usage_fields)
      if (!is.null(def$max_requests)) {
        remaining$max_requests <- if (is.null(remaining$max_requests)) {
          def$max_requests
        } else {
          min(remaining$max_requests, def$max_requests)
        }
      }

      do.call(
        UsageLimits,
        c(remaining, list(on_exceed = limits$on_exceed))
      )
    },

    reserve_delegation_usage = function(delegation_id, limits) {
      fields <- c(
        "max_requests",
        "max_tool_calls",
        "max_input_tokens",
        "max_output_tokens",
        "max_total_tokens",
        "max_cost_usd"
      )
      private$delegation_usage_reservations[[delegation_id]] <- vapply(
        fields,
        function(field) S7::prop(limits, field) %||% 0,
        numeric(1)
      )
      invisible(NULL)
    },

    release_delegation_usage = function(delegation_id) {
      private$delegation_usage_reservations[[delegation_id]] <- NULL
      invisible(NULL)
    },

    reserved_delegation_usage = function() {
      fields <- c(
        "max_requests",
        "max_tool_calls",
        "max_input_tokens",
        "max_output_tokens",
        "max_total_tokens",
        "max_cost_usd"
      )
      reserved <- stats::setNames(numeric(length(fields)), fields)
      for (reservation in private$delegation_usage_reservations) {
        reserved <- reserved + reservation[fields]
      }
      reserved
    },

    prepare_cloned_tool = function(tool) {
      name <- read_optional_value(
        function() tool@name,
        validator = is_nonempty_string
      )
      if (
        identical(name$status, "present") &&
          identical(name$value, "delegate_to_agent")
      ) {
        return(private$adapt_tool(private$create_delegate_tool()))
      }
      private$adapt_tool(tool)
    },

    filter_disallowed_tools = function(tools, disallowed_tools) {
      if (is.null(disallowed_tools) || length(disallowed_tools) == 0) {
        return(tools)
      }

      disallowed <- tolower(trimws(as.character(disallowed_tools)))
      tool_names <- names(tools)
      keep <- vapply(
        seq_along(tools),
        function(index) {
          tool <- tools[[index]]
          label <- if (
            !is.null(tool_names) &&
              length(tool_names) >= index &&
              is_nonempty_string(tool_names[[index]])
          ) {
            tool_names[[index]]
          } else {
            paste0("#", index)
          }
          name <- read_optional_value(
            function() tool@name,
            validator = is_nonempty_string
          )

          if (identical(name$status, "unreadable")) {
            cli_warn(c(
              "Dropping tool {.val {label}} because its name could not be read.",
              "i" = "Tool object class: {.cls {class(tool)}}.",
              "x" = conditionMessage(name$error)
            ))
            return(FALSE)
          }

          if (!identical(name$status, "present")) {
            cli_warn(c(
              "Dropping tool {.val {label}} because it has no usable name.",
              "i" = "Tool object class: {.cls {class(tool)}}."
            ))
            return(FALSE)
          }

          !tolower(trimws(name$value)) %in% disallowed
        },
        logical(1)
      )

      tools[keep]
    },

    .sub_agent_defs = list(),
    .delegation_policy = NULL,
    .delegation_disclosure = NULL,
    delegation_bindings = list(),
    subagent_runs = list(),
    active_subagents = list(),
    delegation_sources = list(),
    delegation_scope = list(),
    delegation_max_bytes = 65536L,
    delegation_usage_reservations = list()
  )
)
